/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/simulation_interfaces\srv/DeleteEntity.c
  Source: C:\Dev\DataTypes\ROS\simulation_interfaces\srv\DeleteEntity.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "DeleteEntity.h"

static const uint32_t simulation_interfaces_srv_DeleteEntity_Request_ops [] =
{
  /* DeleteEntity_Request */
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (simulation_interfaces_srv_DeleteEntity_Request, entity),
  DDS_OP_RTS
};

const dds_topic_descriptor_t simulation_interfaces_srv_DeleteEntity_Request_desc =
{
  .m_size = sizeof (simulation_interfaces_srv_DeleteEntity_Request),
  .m_align = dds_alignof (simulation_interfaces_srv_DeleteEntity_Request),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "simulation_interfaces::srv::DeleteEntity_Request",
  .m_keys = NULL,
  .m_nops = 2,
  .m_ops = simulation_interfaces_srv_DeleteEntity_Request_ops,
  .m_meta = ""
};

static const uint32_t simulation_interfaces_srv_DeleteEntity_Response_ops [] =
{
  /* DeleteEntity_Response */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (simulation_interfaces_srv_DeleteEntity_Response, result), (3u << 16u) + 4u /* Result */,
  DDS_OP_RTS,

  /* Result */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (simulation_interfaces_msg_Result, result),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (simulation_interfaces_msg_Result, error_message),
  DDS_OP_RTS
};

const dds_topic_descriptor_t simulation_interfaces_srv_DeleteEntity_Response_desc =
{
  .m_size = sizeof (simulation_interfaces_srv_DeleteEntity_Response),
  .m_align = dds_alignof (simulation_interfaces_srv_DeleteEntity_Response),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "simulation_interfaces::srv::DeleteEntity_Response",
  .m_keys = NULL,
  .m_nops = 5,
  .m_ops = simulation_interfaces_srv_DeleteEntity_Response_ops,
  .m_meta = ""
};

