/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/simulation_interfaces\srv/DeleteEntity.h
  Source: C:\Dev\DataTypes\ROS\simulation_interfaces\srv\DeleteEntity.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_SRV_DELETEENTITY_H_83BD9F83886FF06E73E204CE1DEA77DB
#define DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_SRV_DELETEENTITY_H_83BD9F83886FF06E73E204CE1DEA77DB

#include "simulation_interfaces/msg/Result.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct simulation_interfaces_srv_DeleteEntity_Request
{
  char * entity;
} simulation_interfaces_srv_DeleteEntity_Request;

extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t simulation_interfaces_srv_DeleteEntity_Request_desc;

#define simulation_interfaces_srv_DeleteEntity_Request__alloc() \
((simulation_interfaces_srv_DeleteEntity_Request*) dds_alloc (sizeof (simulation_interfaces_srv_DeleteEntity_Request)));

#define simulation_interfaces_srv_DeleteEntity_Request_free(d,o) \
dds_sample_free ((d), &simulation_interfaces_srv_DeleteEntity_Request_desc, (o))

typedef struct simulation_interfaces_srv_DeleteEntity_Response
{
  struct simulation_interfaces_msg_Result result;
} simulation_interfaces_srv_DeleteEntity_Response;

extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t simulation_interfaces_srv_DeleteEntity_Response_desc;

#define simulation_interfaces_srv_DeleteEntity_Response__alloc() \
((simulation_interfaces_srv_DeleteEntity_Response*) dds_alloc (sizeof (simulation_interfaces_srv_DeleteEntity_Response)));

#define simulation_interfaces_srv_DeleteEntity_Response_free(d,o) \
dds_sample_free ((d), &simulation_interfaces_srv_DeleteEntity_Response_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_SRV_DELETEENTITY_H_83BD9F83886FF06E73E204CE1DEA77DB */
