/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/simulation_interfaces\srv/GetEntities.h
  Source: C:\Dev\DataTypes\ROS\simulation_interfaces\srv\GetEntities.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_SRV_GETENTITIES_H_C536E82DC198237E01DE28CCDDAB7FF6
#define DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_SRV_GETENTITIES_H_C536E82DC198237E01DE28CCDDAB7FF6

#include "simulation_interfaces\msg\EntityFilters.h"

#include "simulation_interfaces\msg\Result.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct simulation_interfaces_srv_GetEntities_Request
{
  struct simulation_interfaces_msg_EntityFilters filters;
} simulation_interfaces_srv_GetEntities_Request;

extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t simulation_interfaces_srv_GetEntities_Request_desc;

#define simulation_interfaces_srv_GetEntities_Request__alloc() \
((simulation_interfaces_srv_GetEntities_Request*) dds_alloc (sizeof (simulation_interfaces_srv_GetEntities_Request)));

#define simulation_interfaces_srv_GetEntities_Request_free(d,o) \
dds_sample_free ((d), &simulation_interfaces_srv_GetEntities_Request_desc, (o))

#ifndef DDS_SEQUENCE_STRING_DEFINED
#define DDS_SEQUENCE_STRING_DEFINED
typedef struct dds_sequence_string
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} dds_sequence_string;

#define dds_sequence_string__alloc() \
((dds_sequence_string*) dds_alloc (sizeof (dds_sequence_string)));

#define dds_sequence_string_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
#endif /* DDS_SEQUENCE_STRING_DEFINED */

typedef struct simulation_interfaces_srv_GetEntities_Response
{
  struct simulation_interfaces_msg_Result result;
  dds_sequence_string entities;
} simulation_interfaces_srv_GetEntities_Response;

extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t simulation_interfaces_srv_GetEntities_Response_desc;

#define simulation_interfaces_srv_GetEntities_Response__alloc() \
((simulation_interfaces_srv_GetEntities_Response*) dds_alloc (sizeof (simulation_interfaces_srv_GetEntities_Response)));

#define simulation_interfaces_srv_GetEntities_Response_free(d,o) \
dds_sample_free ((d), &simulation_interfaces_srv_GetEntities_Response_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_SRV_GETENTITIES_H_C536E82DC198237E01DE28CCDDAB7FF6 */
