/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/simulation_interfaces\srv/SpawnEntity.h
  Source: C:\Dev\DataTypes\ROS\simulation_interfaces\srv\SpawnEntity.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_SRV_SPAWNENTITY_H_1A6792BF50A937CF63033E5FBAC3C369
#define DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_SRV_SPAWNENTITY_H_1A6792BF50A937CF63033E5FBAC3C369

#include "geometry_msgs\msg\PoseStamped.h"

#include "simulation_interfaces\msg\Result.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct simulation_interfaces_srv_SpawnEntity_Request
{
  char * name;
  bool allow_renaming;
  char * uri;
  char * resource_string;
  char * entity_namespace;
  struct geometry_msgs_msg_PoseStamped initial_pose;
} simulation_interfaces_srv_SpawnEntity_Request;

extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t simulation_interfaces_srv_SpawnEntity_Request_desc;

#define simulation_interfaces_srv_SpawnEntity_Request__alloc() \
((simulation_interfaces_srv_SpawnEntity_Request*) dds_alloc (sizeof (simulation_interfaces_srv_SpawnEntity_Request)));

#define simulation_interfaces_srv_SpawnEntity_Request_free(d,o) \
dds_sample_free ((d), &simulation_interfaces_srv_SpawnEntity_Request_desc, (o))

#define simulation_interfaces_srv_SpawnEntity_Response_Constants_NAME_NOT_UNIQUE 101
#define simulation_interfaces_srv_SpawnEntity_Response_Constants_NAME_INVALID 102
#define simulation_interfaces_srv_SpawnEntity_Response_Constants_UNSUPPORTED_FORMAT 103
#define simulation_interfaces_srv_SpawnEntity_Response_Constants_NO_RESOURCE 104
#define simulation_interfaces_srv_SpawnEntity_Response_Constants_NAMESPACE_INVALID 105
#define simulation_interfaces_srv_SpawnEntity_Response_Constants_RESOURCE_PARSE_ERROR 106
#define simulation_interfaces_srv_SpawnEntity_Response_Constants_MISSING_ASSETS 107
#define simulation_interfaces_srv_SpawnEntity_Response_Constants_UNSUPPORTED_ASSETS 108
#define simulation_interfaces_srv_SpawnEntity_Response_Constants_INVALID_POSE 109
typedef struct simulation_interfaces_srv_SpawnEntity_Response
{
  struct simulation_interfaces_msg_Result result;
  char * entity_name;
} simulation_interfaces_srv_SpawnEntity_Response;

extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t simulation_interfaces_srv_SpawnEntity_Response_desc;

#define simulation_interfaces_srv_SpawnEntity_Response__alloc() \
((simulation_interfaces_srv_SpawnEntity_Response*) dds_alloc (sizeof (simulation_interfaces_srv_SpawnEntity_Response)));

#define simulation_interfaces_srv_SpawnEntity_Response_free(d,o) \
dds_sample_free ((d), &simulation_interfaces_srv_SpawnEntity_Response_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_SRV_SPAWNENTITY_H_1A6792BF50A937CF63033E5FBAC3C369 */
