/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/simulation_interfaces\srv/SpawnEntity.c
  Source: C:\Dev\DataTypes\ROS\simulation_interfaces\srv\SpawnEntity.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "SpawnEntity.h"

static const uint32_t simulation_interfaces_srv_SpawnEntity_Request_ops [] =
{
  /* SpawnEntity_Request */
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (simulation_interfaces_srv_SpawnEntity_Request, name),
  DDS_OP_ADR | DDS_OP_TYPE_BLN, offsetof (simulation_interfaces_srv_SpawnEntity_Request, allow_renaming),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (simulation_interfaces_srv_SpawnEntity_Request, uri),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (simulation_interfaces_srv_SpawnEntity_Request, resource_string),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (simulation_interfaces_srv_SpawnEntity_Request, entity_namespace),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (simulation_interfaces_srv_SpawnEntity_Request, initial_pose), (3u << 16u) + 4u /* PoseStamped */,
  DDS_OP_RTS,

  /* PoseStamped */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_PoseStamped, header), (3u << 16u) + 7u /* Header */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_PoseStamped, pose), (3u << 16u) + 15u /* Pose */,
  DDS_OP_RTS,

  /* Header */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (std_msgs_msg_Header, frame_id),
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS,

  /* Pose */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Pose, position), (3u << 16u) + 7u /* Point */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Pose, orientation), (3u << 16u) + 11u /* Quaternion */,
  DDS_OP_RTS,

  /* Point */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, z),
  DDS_OP_RTS,

  /* Quaternion */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, z),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, w),
  DDS_OP_RTS
};

const dds_topic_descriptor_t simulation_interfaces_srv_SpawnEntity_Request_desc =
{
  .m_size = sizeof (simulation_interfaces_srv_SpawnEntity_Request),
  .m_align = dds_alignof (simulation_interfaces_srv_SpawnEntity_Request),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "simulation_interfaces::srv::SpawnEntity_Request",
  .m_keys = NULL,
  .m_nops = 28,
  .m_ops = simulation_interfaces_srv_SpawnEntity_Request_ops,
  .m_meta = ""
};

static const uint32_t simulation_interfaces_srv_SpawnEntity_Response_ops [] =
{
  /* SpawnEntity_Response */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (simulation_interfaces_srv_SpawnEntity_Response, result), (3u << 16u) + 6u /* Result */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (simulation_interfaces_srv_SpawnEntity_Response, entity_name),
  DDS_OP_RTS,

  /* Result */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (simulation_interfaces_msg_Result, result),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (simulation_interfaces_msg_Result, error_message),
  DDS_OP_RTS
};

const dds_topic_descriptor_t simulation_interfaces_srv_SpawnEntity_Response_desc =
{
  .m_size = sizeof (simulation_interfaces_srv_SpawnEntity_Response),
  .m_align = dds_alignof (simulation_interfaces_srv_SpawnEntity_Response),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "simulation_interfaces::srv::SpawnEntity_Response",
  .m_keys = NULL,
  .m_nops = 6,
  .m_ops = simulation_interfaces_srv_SpawnEntity_Response_ops,
  .m_meta = ""
};

