/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/msg/TFMessage.c
  Source: C:\Dev\DataTypes\ROS\tf2_msgs\msg\TFMessage.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#include "TFMessage.h"

static const uint32_t tf2_msgs_msg_TFMessage_ops[] =
{
	/* TFMessage */
	DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof(tf2_msgs_msg_TFMessage, transforms), sizeof(geometry_msgs_msg_TransformStamped), (4u << 16u) + 5u /* TransformStamped */,
	DDS_OP_RTS,

	/* TransformStamped */
	DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof(geometry_msgs_msg_TransformStamped, header), (3u << 16u) + 9u /* Header */,
	DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof(geometry_msgs_msg_TransformStamped, child_frame_id),
	DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof(geometry_msgs_msg_TransformStamped, transform), (3u << 16u) + 15u /* Transform */,
	DDS_OP_RTS,

	/* Header */
	DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof(std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
	DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof(std_msgs_msg_Header, frame_id),
	DDS_OP_RTS,

	/* Time */
	DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof(builtin_interfaces_msg_Time, sec),
	DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof(builtin_interfaces_msg_Time, nanosec),
	DDS_OP_RTS,

	/* Transform */
	DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof(geometry_msgs_msg_Transform, translation), (3u << 16u) + 7u /* Vector3 */,
	DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof(geometry_msgs_msg_Transform, rotation), (3u << 16u) + 11u /* Quaternion */,
	DDS_OP_RTS,

	/* Vector3 */
	DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof(geometry_msgs_msg_Vector3, x),
	DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof(geometry_msgs_msg_Vector3, y),
	DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof(geometry_msgs_msg_Vector3, z),
	DDS_OP_RTS,

	/* Quaternion */
	DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof(geometry_msgs_msg_Quaternion, x),
	DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof(geometry_msgs_msg_Quaternion, y),
	DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof(geometry_msgs_msg_Quaternion, z),
	DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof(geometry_msgs_msg_Quaternion, w),
	DDS_OP_RTS
};

const dds_topic_descriptor_t tf2_msgs_msg_TFMessage_desc =
{
  .m_size = sizeof(tf2_msgs_msg_TFMessage),
  .m_align = dds_alignof(tf2_msgs_msg_TFMessage),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "tf2_msgs::msg::dds_::TFMessage_",
  .m_keys = NULL,
  .m_nops = 24,
  .m_ops = tf2_msgs_msg_TFMessage_ops,
  .m_meta = ""
};

