/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSCameraInfo.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSCameraInfo.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "sensor_msgs/msg/CameraInfo.h"

#include "SensorMsgs/Msg/ROSRegionOfInterest.h"
#include "StdMsgs/Msg/ROSHeader.h"

#include "ROSCameraInfo.generated.h" 








USTRUCT(Blueprintable)
struct FROSCameraInfo
{
    GENERATED_BODY()

public:

    FROSCameraInfo()
    {
        K.SetNumZeroed(9);
        R.SetNumZeroed(9);
        P.SetNumZeroed(9);
    };

    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSHeader Header;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int Height;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int Width;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString DistortionModel;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<double> D;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<double> K;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<double> R;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<double> P;
    
    UPROPERTY(EditAnywhere)
    unsigned int BinningX;
    
    UPROPERTY(EditAnywhere)
    unsigned int BinningY;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSRegionOfInterest Roi;

    void DDSToUE (const sensor_msgs_msg_CameraInfo& InData);
    void UEToDDS (sensor_msgs_msg_CameraInfo& OutData);
};




DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSCameraInfoCallback, const FROSCameraInfo, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UCameraInfo_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

public:

    UPROPERTY(BlueprintAssignable)
    FROSCameraInfoCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSCameraInfo& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSCameraInfo Input);

private:
    sensor_msgs_msg_CameraInfo* Data;
};