/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSChannelFloat32.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSChannelFloat32.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Utils/ConvertUtils.h"
#include "sensor_msgs/msg/ChannelFloat32.h"

#include "ROSChannelFloat32.generated.h" 






USTRUCT(Blueprintable)
struct FROSChannelFloat32
{
    GENERATED_BODY()

public:

    FROSChannelFloat32()
    {

    };

    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Name;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<float> Values;
    
    void DDSToUE (const sensor_msgs_msg_ChannelFloat32& InData);
    void UEToDDS (sensor_msgs_msg_ChannelFloat32& OutData);
};
