/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSImu.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSImu.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"

#include "sensor_msgs/msg/Imu.h"

#include "StdMsgs/Msg/ROSHeader.h"

#include "ROSImu.generated.h" 






USTRUCT(Blueprintable)
struct FROSImu
{
    GENERATED_BODY()
    
    FROSImu()
    {
        OrientationCovariance.SetNumZeroed(9);
        AngularVelocityCovariance.SetNumZeroed(9);
        LinearAccelerationCovariance.SetNumZeroed(9);
    };

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSHeader Header;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FQuat Orientation = FQuat::Identity;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<double> OrientationCovariance;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FVector AngularVelocity = FVector::ZeroVector;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<double> AngularVelocityCovariance;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FVector LinearAcceleration = FVector::ZeroVector;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<double> LinearAccelerationCovariance;

    
    void DDSToUE(const sensor_msgs_msg_Imu& InData);
    void UEToDDS(sensor_msgs_msg_Imu& OutData);
};



DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSImuCallback, const FROSImu, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UImu_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

public:

    UPROPERTY(BlueprintAssignable)
    FROSImuCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSImu& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSImu Input);

private:
    sensor_msgs_msg_Imu* Data;
};