/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSJointState.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSJointState.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "sensor_msgs/msg/JointState.h"

#include "StdMsgs/Msg/ROSHeader.h"

#include "ROSJointState.generated.h" 





USTRUCT(Blueprintable)
struct FROSJointState
{
    GENERATED_BODY()
    
    FROSJointState()
    {

    };
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSHeader Header;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FString> Name;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<double> Position;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<double> Velocity;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<double> Effort;
    
    
    void DDSToUE(const sensor_msgs_msg_JointState& InData);
    void UEToDDS(sensor_msgs_msg_JointState& OutData);
};




DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSJointStateCallback, const FROSJointState, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UJointState_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

public:

    UPROPERTY(BlueprintAssignable)
    FROSJointStateCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSJointState& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSJointState Input);

private:
    sensor_msgs_msg_JointState* Data;
};