/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSLaserScan.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSLaserScan.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "sensor_msgs/msg/LaserScan.h"

#include "StdMsgs/Msg/ROSHeader.h"

#include "ROSLaserScan.generated.h" 




USTRUCT(Blueprintable)
struct FROSLaserScan
{
    GENERATED_BODY()

    FROSLaserScan()
    {

    };
    
    UPROPERTY(EditAnywhere)
    FROSHeader Header;
    
    UPROPERTY(EditAnywhere)
    float AngleMin;
    
    UPROPERTY(EditAnywhere)
    float AngleMax;
    
    UPROPERTY(EditAnywhere)
    float AngleIncrement;
    
    UPROPERTY(EditAnywhere)
    float TimeIncrement;
    
    UPROPERTY(EditAnywhere)
    float ScanTime;
    
    UPROPERTY(EditAnywhere)
    float RangeMin;
    
    UPROPERTY(EditAnywhere)
    float RangeMax;
    
    UPROPERTY(EditAnywhere)
    TArray<float> Ranges;
    
    UPROPERTY(EditAnywhere)
    TArray<float> Intensities;
    

    void DDSToUE (const sensor_msgs_msg_LaserScan& InData);
    void UEToDDS (sensor_msgs_msg_LaserScan& OutData);
};



DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSLaserScanCallback, const FROSLaserScan, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API ULaserScan_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

public:

    UPROPERTY(BlueprintAssignable)
    FROSLaserScanCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSLaserScan& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSLaserScan Input);

private:
    sensor_msgs_msg_LaserScan* Data;
};