/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSNavSatFix.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSNavSatFix.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "sensor_msgs/msg/NavSatFix.h"

#include "SensorMsgs/Msg/ROSNavSatStatus.h"
#include "StdMsgs/Msg/ROSHeader.h"

#include "ROSNavSatFix.generated.h" 




USTRUCT(Blueprintable)
struct FROSNavSatFix
{
    GENERATED_BODY()

    FROSNavSatFix()
    {
        PositionCovariance.SetNumZeroed(9);
    };

    // Covariance Type constants
    static constexpr uint8 CovarianceTypeUnknown = 0;
    static constexpr uint8 CovarianceTypeApproximated = 1;
    static constexpr uint8 CovarianceTypeDiagonalKnown = 2;
    static constexpr uint8 CovarianceTypeKnown = 3;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSHeader Header;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSNavSatStatus Status;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    double Latitude = 0.0;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    double Longitude = 0.0;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    double Altitude = 0.0;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<double> PositionCovariance;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    uint8 PositionCovarianceType = CovarianceTypeUnknown;
    
    void DDSToUE(const sensor_msgs_msg_NavSatFix& InData);
    void UEToDDS(sensor_msgs_msg_NavSatFix& OutData);
};



DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSNavSatFixCallback, const FROSNavSatFix, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UNavSatFix_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

public:

    UPROPERTY(BlueprintAssignable)
    FROSNavSatFixCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSNavSatFix& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSNavSatFix Input);

private:
    sensor_msgs_msg_NavSatFix* Data;
};