/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSPointCloud2.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSPointCloud2.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"

#include "sensor_msgs/msg/PointCloud2.h"

#include "SensorMsgs/Msg/ROSPointField.h"
#include "StdMsgs/Msg/ROSHeader.h"

#include "ROSPointCloud2.generated.h" 



USTRUCT(Blueprintable)
struct FROSPointCloud2
{
    GENERATED_BODY()

    FROSPointCloud2()
    {

    };

    
    UPROPERTY(EditAnywhere)
    FROSHeader Header;
    
    UPROPERTY(EditAnywhere)
    unsigned int Height;
    
    UPROPERTY(EditAnywhere)
    unsigned int Width;
    
    UPROPERTY(EditAnywhere)
    TArray<FROSPointField> Fields;
    
    UPROPERTY(EditAnywhere)
    bool IsBigendian;
    
    UPROPERTY(EditAnywhere)
    unsigned int PointStep;
    
    UPROPERTY(EditAnywhere)
    unsigned int RowStep;
    
    UPROPERTY(EditAnywhere)
    TArray<uint8> Data;
    
    UPROPERTY(EditAnywhere)
    bool IsDense;
    

    void DDSToUE (const sensor_msgs_msg_PointCloud2& InData);
    void UEToDDS (sensor_msgs_msg_PointCloud2& OutData);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSPointCloud2Callback, const FROSPointCloud2, Data);


UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UPointCloud2_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

    UPROPERTY(BlueprintAssignable)
    FROSPointCloud2Callback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSPointCloud2& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSPointCloud2 Input);

private:
    sensor_msgs_msg_PointCloud2* Data;
};