/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSPointCloud.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSPointCloud.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "sensor_msgs/msg/PointCloud.h"


#include "GeometryMsgs/Msg/ROSPoint32.h"
#include "SensorMsgs/Msg/ROSChannelFloat32.h"
#include "StdMsgs/Msg/ROSHeader.h"

#include "ROSPointCloud.generated.h" 





USTRUCT(Blueprintable)
struct FROSPointCloud
{
    GENERATED_BODY()

    FROSPointCloud()
    {

    };

    
    UPROPERTY(EditAnywhere)
    FROSHeader Header;
    
    UPROPERTY(EditAnywhere)
    TArray<FROSPoint32> Points;
    
    UPROPERTY(EditAnywhere)
    TArray<FROSChannelFloat32> Channels;
    

    void DDSToUE(const sensor_msgs_msg_PointCloud& InData);
    void UEToDDS(sensor_msgs_msg_PointCloud& OutData);
};



DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSPointCloudCallback, const FROSPointCloud, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UPointCloud_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

    UPROPERTY(BlueprintAssignable)
    FROSPointCloudCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSPointCloud& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSPointCloud Input);

private:
    sensor_msgs_msg_PointCloud* Data;
};