/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSRegionOfInterest.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSRegionOfInterest.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "sensor_msgs/msg/RegionOfInterest.h"

#include "ROSRegionOfInterest.generated.h" 







/** @addtogroup {NameDoxygenMessageContainer}
  * @brief {NameDoxygenMessageContainer}
  *
  * @{
  */
USTRUCT(Blueprintable)
struct FROSRegionOfInterest
{
    GENERATED_BODY()

public:
    /**
    * @cond
    */
    FROSRegionOfInterest()
    {

    };
    /**
     * @endcond
     */

    
    UPROPERTY(EditAnywhere)
    unsigned int XOffset;
    
    UPROPERTY(EditAnywhere)
    unsigned int YOffset;
    
    UPROPERTY(EditAnywhere)
    unsigned int Height;
    
    UPROPERTY(EditAnywhere)
    unsigned int Width;
    
    UPROPERTY(EditAnywhere)
    bool DoRectify;
    

    /**
     * @cond
     */
    void DDSToUE (const sensor_msgs_msg_RegionOfInterest& InData) 
    {
        XOffset = InData.x_offset;
        YOffset = InData.y_offset;
        Height = InData.height;
        Width = InData.width;
        DoRectify = InData.do_rectify;
    };

    void UEToDDS (sensor_msgs_msg_RegionOfInterest& OutData) 
    {
        OutData.x_offset = XOffset;
        OutData.y_offset = YOffset;
        OutData.height = Height;
        OutData.width = Width;
        OutData.do_rectify = DoRectify;
    };
    
    /**
     * @endcond
     */
};
/** @} */



DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSRegionOfInterestCallback, const FROSRegionOfInterest, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API URegionOfInterest_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

public:

    UPROPERTY(BlueprintAssignable)
    FROSRegionOfInterestCallback OnDataChanged;

    virtual void Initialize() override {
        Data = sensor_msgs_msg_RegionOfInterest__alloc();
    };

    virtual void Terminate() override {
        sensor_msgs_msg_RegionOfInterest_free(Data, DDS_FREE_ALL);
    };

    UFUNCTION(BlueprintCallable)
    void GetData(FROSRegionOfInterest& Output)
    {
        Output.DDSToUE(*Data);
    };

    UFUNCTION(BlueprintCallable)
    void SetData(FROSRegionOfInterest Input)
    {
        Input.UEToDDS(*Data);
    };

    virtual void ExecuteMessageCallback() override
    {
        FROSRegionOfInterest NewData;
        NewData.DDSToUE(*Data);
        OnDataChanged.Broadcast(NewData);
    };

    virtual void* Get() override
    {
        return Data;
    };

    virtual const dds_topic_descriptor_t* GetTypeDesc() override
    {
        return &sensor_msgs_msg_RegionOfInterest_desc;
    };

private:
    sensor_msgs_msg_RegionOfInterest* Data;
};