/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/simulation_interfaces\msg/Bounds.c
  Source: C:\Dev\DataTypes\ROS\simulation_interfaces\msg\Bounds.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "Bounds.h"

static const uint32_t simulation_interfaces_msg_Bounds_ops [] =
{
  /* Bounds */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (simulation_interfaces_msg_Bounds, type),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (simulation_interfaces_msg_Bounds, points), sizeof (geometry_msgs_msg_Vector3), (4u << 16u) + 5u /* Vector3 */,
  DDS_OP_RTS,

  /* Vector3 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t simulation_interfaces_msg_Bounds_desc =
{
  .m_size = sizeof (simulation_interfaces_msg_Bounds),
  .m_align = dds_alignof (simulation_interfaces_msg_Bounds),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "simulation_interfaces::msg::Bounds",
  .m_keys = NULL,
  .m_nops = 7,
  .m_ops = simulation_interfaces_msg_Bounds_ops,
  .m_meta = ""
};

