/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/simulation_interfaces\msg/Bounds.h
  Source: C:\Dev\DataTypes\ROS\simulation_interfaces\msg\Bounds.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_MSG_BOUNDS_H_AE24B037D3152DD440C32EBC5F2794D7
#define DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_MSG_BOUNDS_H_AE24B037D3152DD440C32EBC5F2794D7

#include "geometry_msgs/msg/Vector3.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define simulation_interfaces_msg_Bounds_Constants_TYPE_EMPTY 0
#define simulation_interfaces_msg_Bounds_Constants_TYPE_BOX 1
#define simulation_interfaces_msg_Bounds_Constants_TYPE_CONVEX_HULL 2
#define simulation_interfaces_msg_Bounds_Constants_TYPE_SPHERE 3
#ifndef DDS_SEQUENCE_GEOMETRY_MSGS_MSG_VECTOR3_DEFINED
#define DDS_SEQUENCE_GEOMETRY_MSGS_MSG_VECTOR3_DEFINED
typedef struct dds_sequence_geometry_msgs_msg_Vector3
{
  uint32_t _maximum;
  uint32_t _length;
  struct geometry_msgs_msg_Vector3 *_buffer;
  bool _release;
} dds_sequence_geometry_msgs_msg_Vector3;

#define dds_sequence_geometry_msgs_msg_Vector3__alloc() \
((dds_sequence_geometry_msgs_msg_Vector3*) dds_alloc (sizeof (dds_sequence_geometry_msgs_msg_Vector3)));

#define dds_sequence_geometry_msgs_msg_Vector3_allocbuf(l) \
((struct geometry_msgs_msg_Vector3 *) dds_alloc ((l) * sizeof (struct geometry_msgs_msg_Vector3)))
#endif /* DDS_SEQUENCE_GEOMETRY_MSGS_MSG_VECTOR3_DEFINED */

typedef struct simulation_interfaces_msg_Bounds
{
  uint8_t type;
  dds_sequence_geometry_msgs_msg_Vector3 points;
} simulation_interfaces_msg_Bounds;

extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t simulation_interfaces_msg_Bounds_desc;

#define simulation_interfaces_msg_Bounds__alloc() \
((simulation_interfaces_msg_Bounds*) dds_alloc (sizeof (simulation_interfaces_msg_Bounds)));

#define simulation_interfaces_msg_Bounds_free(d,o) \
dds_sample_free ((d), &simulation_interfaces_msg_Bounds_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_MSG_BOUNDS_H_AE24B037D3152DD440C32EBC5F2794D7 */
