/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/simulation_interfaces\msg/EntityCategory.h
  Source: C:\Dev\DataTypes\ROS\simulation_interfaces\msg\EntityCategory.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_MSG_ENTITYCATEGORY_H_C6F69FD566C6890923F249F9A09C60F9
#define DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_MSG_ENTITYCATEGORY_H_C6F69FD566C6890923F249F9A09C60F9

#include "CycloneRos.h"
#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define simulation_interfaces_msg_EntityCategory_Constants_CATEGORY_OBJECT 0
#define simulation_interfaces_msg_EntityCategory_Constants_CATEGORY_ROBOT 1
#define simulation_interfaces_msg_EntityCategory_Constants_CATEGORY_HUMAN 2
#define simulation_interfaces_msg_EntityCategory_Constants_CATEGORY_DYNAMIC_OBJECT 4
#define simulation_interfaces_msg_EntityCategory_Constants_CATEGORY_STATIC_OBJECT 5
typedef struct simulation_interfaces_msg_EntityCategory
{
  uint8_t category;
} simulation_interfaces_msg_EntityCategory;

extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t simulation_interfaces_msg_EntityCategory_desc;

#define simulation_interfaces_msg_EntityCategory__alloc() \
((simulation_interfaces_msg_EntityCategory*) dds_alloc (sizeof (simulation_interfaces_msg_EntityCategory)));

#define simulation_interfaces_msg_EntityCategory_free(d,o) \
dds_sample_free ((d), &simulation_interfaces_msg_EntityCategory_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_MSG_ENTITYCATEGORY_H_C6F69FD566C6890923F249F9A09C60F9 */
