/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/simulation_interfaces\msg/EntityFilters.h
  Source: C:\Dev\DataTypes\ROS\simulation_interfaces\msg\EntityFilters.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_MSG_ENTITYFILTERS_H_2B41CC0C483D0BF689FDDBCD275CD510
#define DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_MSG_ENTITYFILTERS_H_2B41CC0C483D0BF689FDDBCD275CD510

#include "simulation_interfaces\msg\Bounds.h"

#include "simulation_interfaces\msg\EntityCategory.h"

#include "simulation_interfaces\msg\TagsFilter.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_SIMULATION_INTERFACES_MSG_ENTITYCATEGORY_DEFINED
#define DDS_SEQUENCE_SIMULATION_INTERFACES_MSG_ENTITYCATEGORY_DEFINED
typedef struct dds_sequence_simulation_interfaces_msg_EntityCategory
{
  uint32_t _maximum;
  uint32_t _length;
  struct simulation_interfaces_msg_EntityCategory *_buffer;
  bool _release;
} dds_sequence_simulation_interfaces_msg_EntityCategory;

#define dds_sequence_simulation_interfaces_msg_EntityCategory__alloc() \
((dds_sequence_simulation_interfaces_msg_EntityCategory*) dds_alloc (sizeof (dds_sequence_simulation_interfaces_msg_EntityCategory)));

#define dds_sequence_simulation_interfaces_msg_EntityCategory_allocbuf(l) \
((struct simulation_interfaces_msg_EntityCategory *) dds_alloc ((l) * sizeof (struct simulation_interfaces_msg_EntityCategory)))
#endif /* DDS_SEQUENCE_SIMULATION_INTERFACES_MSG_ENTITYCATEGORY_DEFINED */

typedef struct simulation_interfaces_msg_EntityFilters
{
  char * filter;
  dds_sequence_simulation_interfaces_msg_EntityCategory categories;
  struct simulation_interfaces_msg_TagsFilter tags;
  struct simulation_interfaces_msg_Bounds bounds;
} simulation_interfaces_msg_EntityFilters;

extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t simulation_interfaces_msg_EntityFilters_desc;

#define simulation_interfaces_msg_EntityFilters__alloc() \
((simulation_interfaces_msg_EntityFilters*) dds_alloc (sizeof (simulation_interfaces_msg_EntityFilters)));

#define simulation_interfaces_msg_EntityFilters_free(d,o) \
dds_sample_free ((d), &simulation_interfaces_msg_EntityFilters_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_DATATYPES_COMPILED_SIMULATION_INTERFACES_MSG_ENTITYFILTERS_H_2B41CC0C483D0BF689FDDBCD275CD510 */
