/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/simulation_interfaces\msg/EntityCategory.c
  Source: C:\Dev\DataTypes\ROS\simulation_interfaces\msg\EntityCategory.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "EntityCategory.h"

static const uint32_t simulation_interfaces_msg_EntityCategory_ops [] =
{
  /* EntityCategory */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (simulation_interfaces_msg_EntityCategory, category),
  DDS_OP_RTS
};

const dds_topic_descriptor_t simulation_interfaces_msg_EntityCategory_desc =
{
  .m_size = sizeof (simulation_interfaces_msg_EntityCategory),
  .m_align = dds_alignof (simulation_interfaces_msg_EntityCategory),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "simulation_interfaces::msg::EntityCategory",
  .m_keys = NULL,
  .m_nops = 2,
  .m_ops = simulation_interfaces_msg_EntityCategory_ops,
  .m_meta = ""
};

