/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/simulation_interfaces\msg/EntityFilters.c
  Source: C:\Dev\DataTypes\ROS\simulation_interfaces\msg\EntityFilters.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "EntityFilters.h"

static const uint32_t simulation_interfaces_msg_EntityFilters_ops [] =
{
  /* EntityFilters */
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (simulation_interfaces_msg_EntityFilters, filter),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (simulation_interfaces_msg_EntityFilters, categories), sizeof (simulation_interfaces_msg_EntityCategory), (4u << 16u) + 11u /* EntityCategory */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (simulation_interfaces_msg_EntityFilters, tags), (3u << 16u) + 10u /* TagsFilter */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (simulation_interfaces_msg_EntityFilters, bounds), (3u << 16u) + 12u /* Bounds */,
  DDS_OP_RTS,

  /* EntityCategory */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (simulation_interfaces_msg_EntityCategory, category),
  DDS_OP_RTS,

  /* TagsFilter */
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STR, offsetof (simulation_interfaces_msg_TagsFilter, tags),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (simulation_interfaces_msg_TagsFilter, filter_mode),
  DDS_OP_RTS,

  /* Bounds */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (simulation_interfaces_msg_Bounds, type),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (simulation_interfaces_msg_Bounds, points), sizeof (geometry_msgs_msg_Vector3), (4u << 16u) + 5u /* Vector3 */,
  DDS_OP_RTS,

  /* Vector3 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t simulation_interfaces_msg_EntityFilters_desc =
{
  .m_size = sizeof (simulation_interfaces_msg_EntityFilters),
  .m_align = dds_alignof (simulation_interfaces_msg_EntityFilters),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "simulation_interfaces::msg::EntityFilters",
  .m_keys = NULL,
  .m_nops = 17,
  .m_ops = simulation_interfaces_msg_EntityFilters_ops,
  .m_meta = ""
};

