/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/simulation_interfaces\msg/TagsFilter.c
  Source: C:\Dev\DataTypes\ROS\simulation_interfaces\msg\TagsFilter.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "TagsFilter.h"

static const uint32_t simulation_interfaces_msg_TagsFilter_ops [] =
{
  /* TagsFilter */
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STR, offsetof (simulation_interfaces_msg_TagsFilter, tags),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (simulation_interfaces_msg_TagsFilter, filter_mode),
  DDS_OP_RTS
};

const dds_topic_descriptor_t simulation_interfaces_msg_TagsFilter_desc =
{
  .m_size = sizeof (simulation_interfaces_msg_TagsFilter),
  .m_align = dds_alignof (simulation_interfaces_msg_TagsFilter),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "simulation_interfaces::msg::TagsFilter",
  .m_keys = NULL,
  .m_nops = 3,
  .m_ops = simulation_interfaces_msg_TagsFilter_ops,
  .m_meta = ""
};

