/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSBounds.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSBounds.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/MRSTopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "simulation_interfaces/msg/Bounds.h"

#include "ROSBounds.generated.h" 


USTRUCT(Blueprintable)
struct FROSBounds
{
    GENERATED_BODY()

    FROSBounds()
    {

    };
    
    static constexpr uint8 Empty = 0;
    static constexpr uint8 Box = 1;
    static constexpr uint8 ConvexHull = 2;
    static constexpr uint8 Sphere = 3;
    
    UPROPERTY(EditAnywhere)
    uint8 Type;
    
    UPROPERTY(EditAnywhere)
    TArray<FVector> Points;
    

    void DDSToUE(const simulation_interfaces_msg_Bounds& InData);
    void UEToDDS(simulation_interfaces_msg_Bounds& OutData);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSBoundsCallback, const FROSBounds, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UBounds_TopicProxy : public UMRSTopicProxy
{
    GENERATED_BODY()

    UPROPERTY(BlueprintAssignable)
    FROSBoundsCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSBounds& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSBounds Input);

private:
    simulation_interfaces_msg_Bounds* Data;
};