/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSEntityCategory.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSEntityCategory.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/MRSTopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "simulation_interfaces/msg/EntityCategory.h"

#include "ROSEntityCategory.generated.h" 

USTRUCT(Blueprintable)
struct FROSEntityCategory
{
    GENERATED_BODY()

    FROSEntityCategory()
    {

    };

    static constexpr uint8 CategoryObject = 0;
    static constexpr uint8 CategoryRobot = 1;
    static constexpr uint8 CategoryHuman = 2;
    static constexpr uint8 CagegoryDynamicObject = 4;
    static constexpr uint8 CategoryStaticObject = 5;

    UPROPERTY(EditAnywhere)
    uint8 Category;
    

    void DDSToUE(const simulation_interfaces_msg_EntityCategory& InData);
    void UEToDDS(simulation_interfaces_msg_EntityCategory& OutData);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSEntityCategoryCallback, const FROSEntityCategory, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UEntityCategory_TopicProxy : public UMRSTopicProxy
{
    GENERATED_BODY()

    UPROPERTY(BlueprintAssignable)
    FROSEntityCategoryCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSEntityCategory& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSEntityCategory Input);

private:
    simulation_interfaces_msg_EntityCategory* Data;
};