/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSEntityFilters.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSEntityFilters.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "ROSBounds.h"
#include "ROSTagsFilter.h"
#include "ROSEntityCategory.h"

#include "Topic/MRSTopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "simulation_interfaces/msg/EntityFilters.h"

#include "ROSEntityFilters.generated.h" 



USTRUCT(Blueprintable)
struct FROSEntityFilters
{
    GENERATED_BODY()

    FROSEntityFilters()
    {

    };

    
    UPROPERTY(EditAnywhere)
    FString Filter;
    
    UPROPERTY(EditAnywhere)
    TArray<FROSEntityCategory> Categories;
    
    UPROPERTY(EditAnywhere)
    FROSTagsFilter Tags;
    
    UPROPERTY(EditAnywhere)
    FROSBounds Bounds;
    

    void DDSToUE(const simulation_interfaces_msg_EntityFilters& InData);
    void UEToDDS(simulation_interfaces_msg_EntityFilters& OutData);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSEntityFiltersCallback, const FROSEntityFilters, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UEntityFilters_TopicProxy : public UMRSTopicProxy
{
    GENERATED_BODY()

    UPROPERTY(BlueprintAssignable)
    FROSEntityFiltersCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSEntityFilters& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSEntityFilters Input);

private:
    simulation_interfaces_msg_EntityFilters* Data;
};