/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSResult.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSResult.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/MRSTopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "simulation_interfaces/msg/Result.h"

#include "ROSResult.generated.h" 

#define SIMULATION_INTERFACES_MSG_RESULT_CONSTANTS__RESULT_FEATURE_UNSUPPORTED 0
#define SIMULATION_INTERFACES_MSG_RESULT_CONSTANTS__RESULT_OK 1
#define SIMULATION_INTERFACES_MSG_RESULT_CONSTANTS__RESULT_NOT_FOUND 2
#define SIMULATION_INTERFACES_MSG_RESULT_CONSTANTS__RESULT_INCORRECT_STATE 3
#define SIMULATION_INTERFACES_MSG_RESULT_CONSTANTS__RESULT_OPERATION_FAILED 4


USTRUCT(Blueprintable)
struct FROSResult
{
    GENERATED_BODY()

    FROSResult()
    {

    };

    
    UPROPERTY(EditAnywhere)
    uint8 Result;
    
    UPROPERTY(EditAnywhere)
    FString ErrorMessage;
    

    void DDSToUE(const simulation_interfaces_msg_Result& InData);
    void UEToDDS(simulation_interfaces_msg_Result& OutData);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSResultCallback, const FROSResult, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UResult_TopicProxy : public UMRSTopicProxy
{
    GENERATED_BODY()

    UPROPERTY(BlueprintAssignable)
    FROSResultCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSResult& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSResult Input);

private:
    simulation_interfaces_msg_Result* Data;
};