/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSTagsFilter.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSTagsFilter.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/MRSTopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "simulation_interfaces/msg/TagsFilter.h"

#include "ROSTagsFilter.generated.h" 

USTRUCT(Blueprintable)
struct FROSTagsFilter
{
    GENERATED_BODY()

    FROSTagsFilter()
    {

    };

    static constexpr uint8 FilterModeAny = 0;
    static constexpr uint8 FilterModeAll = 1;

    UPROPERTY(EditAnywhere)
    TArray<FString> Tags;
    
    UPROPERTY(EditAnywhere)
    uint8 FilterMode;
    

    void DDSToUE(const simulation_interfaces_msg_TagsFilter& InData);
    void UEToDDS(simulation_interfaces_msg_TagsFilter& OutData);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSTagsFilterCallback, const FROSTagsFilter, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UTagsFilter_TopicProxy : public UMRSTopicProxy
{
    GENERATED_BODY()

    UPROPERTY(BlueprintAssignable)
    FROSTagsFilterCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSTagsFilter& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSTagsFilter Input);

private:
    simulation_interfaces_msg_TagsFilter* Data;
};