/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/msg/Clock.c
  Source: C:\Dev\DataTypes\ROS\rosgraph_msgs\msg\Clock.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#include "Clock.h"

static const uint32_t rosgraph_msgs_msg_Clock_ops [] =
{
  /* Clock */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (rosgraph_msgs_msg_Clock, clock), (3u << 16u) + 4u /* Time */,
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS
};

const dds_topic_descriptor_t rosgraph_msgs_msg_Clock_desc =
{
  .m_size = sizeof (rosgraph_msgs_msg_Clock),
  .m_align = dds_alignof (rosgraph_msgs_msg_Clock),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "rosgraph_msgs::msg::dds_::Clock_",
  .m_keys = NULL,
  .m_nops = 5,
  .m_ops = rosgraph_msgs_msg_Clock_ops,
  .m_meta = ""
};

