/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\DataTypes\COMPILED/msg/Clock.h
  Source: C:\Dev\DataTypes\ROS\rosgraph_msgs\msg\Clock.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_C__DEV_DATATYPES_COMPILED_MSG_CLOCK_H
#define DDSC_C__DEV_DATATYPES_COMPILED_MSG_CLOCK_H

#include "builtin_interfaces/msg/Time.h"

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct rosgraph_msgs_msg_Clock
{
  struct builtin_interfaces_msg_Time clock;
} rosgraph_msgs_msg_Clock;

extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t rosgraph_msgs_msg_Clock_desc;

#define rosgraph_msgs_msg_Clock__alloc() \
((rosgraph_msgs_msg_Clock*) dds_alloc (sizeof (rosgraph_msgs_msg_Clock)));

#define rosgraph_msgs_msg_Clock_free(d,o) \
dds_sample_free ((d), &rosgraph_msgs_msg_Clock_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_DATATYPES_COMPILED_MSG_CLOCK_H */
