/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSPoseStamped.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSPoseStamped.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "geometry_msgs/msg/PoseStamped.h"

#include "GeometryMsgs/Msg/ROSPose.h"
#include "StdMsgs/Msg/ROSHeader.h"

#include "ROSPoseStamped.generated.h" 







/** @addtogroup {NameDoxygenMessageContainer}
  * @brief {NameDoxygenMessageContainer}
  *
  * @{
  */
USTRUCT(Blueprintable)
struct FROSPoseStamped
{
    GENERATED_BODY()

public:
    /**
    * @cond
    */
    FROSPoseStamped()
    {

    };
    /**
     * @endcond
     */

    
    UPROPERTY(EditAnywhere)
    FROSHeader Header;
    
    UPROPERTY(EditAnywhere)
    FROSPose Pose;
    

    /**
     * @cond
     */
    void DDSToUE (const geometry_msgs_msg_PoseStamped& InData) 
    {
        Header.DDSToUE(InData.header);
        Pose.DDSToUE(InData.pose);
    };

    void UEToDDS (geometry_msgs_msg_PoseStamped& OutData) 
    {
        Header.UEToDDS(OutData.header);
        Pose.UEToDDS(OutData.pose);
    };
    
    /**
     * @endcond
     */
};
/** @} */



DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSPoseStampedCallback, const FROSPoseStamped, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UPoseStamped_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

public:

    UPROPERTY(BlueprintAssignable)
    FROSPoseStampedCallback OnDataChanged;

    virtual void Initialize() override {
        Data = geometry_msgs_msg_PoseStamped__alloc();
    };

    virtual void Terminate() override {
        geometry_msgs_msg_PoseStamped_free(Data, DDS_FREE_ALL);
    };

    UFUNCTION(BlueprintCallable)
    void GetData(FROSPoseStamped& Output)
    {
        Output.DDSToUE(*Data);
    };

    UFUNCTION(BlueprintCallable)
    void SetData(FROSPoseStamped Input)
    {
        Input.UEToDDS(*Data);
    };

    virtual void ExecuteMessageCallback() override
    {
        FROSPoseStamped NewData;
        NewData.DDSToUE(*Data);
        OnDataChanged.Broadcast(NewData);
    };

    virtual void* Get() override
    {
        return Data;
    };

    virtual const dds_topic_descriptor_t* GetTypeDesc() override
    {
        return &geometry_msgs_msg_PoseStamped_desc;
    };

private:
    geometry_msgs_msg_PoseStamped* Data;
};