/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSPoint.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSPoint.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "geometry_msgs/msg/Point.h"

#include "ROSPoint.generated.h" 







/** @addtogroup {NameDoxygenMessageContainer}
  * @brief {NameDoxygenMessageContainer}
  *
  * @{
  */
USTRUCT(Blueprintable)
struct FROSPoint
{
    GENERATED_BODY()

public:
    /**
    * @cond
    */
    FROSPoint()
    {

    };
    /**
     * @endcond
     */

    
    UPROPERTY(EditAnywhere)
    double X;
    
    UPROPERTY(EditAnywhere)
    double Y;
    
    UPROPERTY(EditAnywhere)
    double Z;
    

    /**
     * @cond
     */
    void DDSToUE (const geometry_msgs_msg_Point& InData) 
    {
        X = InData.x;
        Y = InData.y;
        Z = InData.z;
    };

    void UEToDDS (geometry_msgs_msg_Point& OutData) 
    {
        OutData.x = X;
        OutData.y = Y;
        OutData.z = Z;
    };
    
    /**
     * @endcond
     */
};
/** @} */



DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSPointCallback, const FROSPoint, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UPoint_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

public:

    UPROPERTY(BlueprintAssignable)
    FROSPointCallback OnDataChanged;

    virtual void Initialize() override {
        Data = geometry_msgs_msg_Point__alloc();
    };

    virtual void Terminate() override {
        geometry_msgs_msg_Point_free(Data, DDS_FREE_ALL);
    };

    UFUNCTION(BlueprintCallable)
    void GetData(FROSPoint& Output)
    {
        Output.DDSToUE(*Data);
    };

    UFUNCTION(BlueprintCallable)
    void SetData(FROSPoint Input)
    {
        Input.UEToDDS(*Data);
    };

    virtual void ExecuteMessageCallback() override
    {
        FROSPoint NewData;
        NewData.DDSToUE(*Data);
        OnDataChanged.Broadcast(NewData);
    };

    virtual void* Get() override
    {
        return Data;
    };

    virtual const dds_topic_descriptor_t* GetTypeDesc() override
    {
        return &geometry_msgs_msg_Point_desc;
    };

private:
    geometry_msgs_msg_Point* Data;
};