/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSPoint32.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSPoint32.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"

#include "geometry_msgs/msg/Point32.h"


#include "ROSPoint32.generated.h" 






USTRUCT(Blueprintable)
struct FROSPoint32
{
    GENERATED_BODY()

    FROSPoint32()
    {

    };

    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float X = 0.0f;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float Y = 0.0f;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float Z = 0.0f;
    

    void DDSToUE(const geometry_msgs_msg_Point32& InData);
    void UEToDDS(geometry_msgs_msg_Point32& OutData);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSPoint32Callback, const FROSPoint32, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UPoint32_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

    UPROPERTY(BlueprintAssignable)
    FROSPoint32Callback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSPoint32& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSPoint32 Input);

private:
    geometry_msgs_msg_Point32* Data;
};