/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSPointStamped.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSPointStamped.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "geometry_msgs/msg/PointStamped.h"
#include "GeometryMsgs/Msg/ROSPoint.h"
#include "StdMsgs/Msg/ROSHeader.h"
#include "ROSPointStamped.generated.h" 







/** @addtogroup {NameDoxygenMessageContainer}
  * @brief {NameDoxygenMessageContainer}
  *
  * @{
  */
USTRUCT(Blueprintable)
struct FROSPointStamped
{
    GENERATED_BODY()

public:
    /**
    * @cond
    */
    FROSPointStamped()
    {

    };
    /**
     * @endcond
     */

    
    UPROPERTY(EditAnywhere)
    FROSHeader Header;
    
    UPROPERTY(EditAnywhere)
    FROSPoint Point;
    

    /**
     * @cond
     */
    void DDSToUE (const geometry_msgs_msg_PointStamped& InData) 
    {
        Header.DDSToUE(InData.header);
        Point.DDSToUE(InData.point);
    };

    void UEToDDS (geometry_msgs_msg_PointStamped& OutData) 
    {
        Header.UEToDDS(OutData.header);
        Point.UEToDDS(OutData.point);
    };
    
    /**
     * @endcond
     */
};
/** @} */



DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSPointStampedCallback, const FROSPointStamped, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UPointStamped_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

public:

    UPROPERTY(BlueprintAssignable)
    FROSPointStampedCallback OnDataChanged;

    virtual void Initialize() override {
        Data = geometry_msgs_msg_PointStamped__alloc();
    };

    virtual void Terminate() override {
        geometry_msgs_msg_PointStamped_free(Data, DDS_FREE_ALL);
    };

    UFUNCTION(BlueprintCallable)
    void GetData(FROSPointStamped& Output)
    {
        Output.DDSToUE(*Data);
    };

    UFUNCTION(BlueprintCallable)
    void SetData(FROSPointStamped Input)
    {
        Input.UEToDDS(*Data);
    };

    virtual void ExecuteMessageCallback() override
    {
        FROSPointStamped NewData;
        NewData.DDSToUE(*Data);
        OnDataChanged.Broadcast(NewData);
    };

    virtual void* Get() override
    {
        return Data;
    };

    virtual const dds_topic_descriptor_t* GetTypeDesc() override
    {
        return &geometry_msgs_msg_PointStamped_desc;
    };

private:
    geometry_msgs_msg_PointStamped* Data;
};