/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSPointStamped.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSPointStamped.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "geometry_msgs/msg/PointStamped.h"
#include "GeometryMsgs/Msg/ROSPoint.h"
#include "StdMsgs/Msg/ROSHeader.h"
#include "ROSPointStamped.generated.h" 







USTRUCT(Blueprintable)
struct FROSPointStamped
{
    GENERATED_BODY()

    FROSPointStamped()
    {

    };

    
    UPROPERTY(EditAnywhere)
    FROSHeader Header;
    
    UPROPERTY(EditAnywhere)
    FROSPoint Point;
    

    void DDSToUE(const geometry_msgs_msg_PointStamped& InData);
    void UEToDDS(geometry_msgs_msg_PointStamped& OutData);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSPointStampedCallback, const FROSPointStamped, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UPointStamped_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

    UPROPERTY(BlueprintAssignable)
    FROSPointStampedCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSPointStamped& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSPointStamped Input);

private:
    geometry_msgs_msg_PointStamped* Data;
};