/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSPoseWithCovarianceStamped.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSPoseWithCovarianceStamped.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/MRSTopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "geometry_msgs/msg/PoseWithCovarianceStamped.h"
#include "GeometryMsgs/Msg/ROSPoseWithCovariance.h"
#include "StdMsgs/Msg/ROSHeader.h"

#include "ROSPoseWithCovarianceStamped.generated.h" 







USTRUCT(Blueprintable)
struct FROSPoseWithCovarianceStamped
{
    GENERATED_BODY()

    FROSPoseWithCovarianceStamped()
    {

    };

    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSHeader Header;
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSPoseWithCovariance Pose;
    

    void DDSToUE(const geometry_msgs_msg_PoseWithCovarianceStamped& InData);
    void UEToDDS(geometry_msgs_msg_PoseWithCovarianceStamped& OutData);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSPoseWithCovarianceStampedCallback, const FROSPoseWithCovarianceStamped, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UPoseWithCovarianceStamped_TopicProxy : public UMRSTopicProxy
{
    GENERATED_BODY()

    UPROPERTY(BlueprintAssignable)
    FROSPoseWithCovarianceStampedCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSPoseWithCovarianceStamped& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSPoseWithCovarianceStamped Input);

private:
    geometry_msgs_msg_PoseWithCovarianceStamped* Data;
};