/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSTransformStamped.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSTransformStamped.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Utils/ConvertUtils.h"


#include "geometry_msgs/msg/TransformStamped.h"


#include "GeometryMsgs/Msg/ROSTransform.h"
#include "StdMsgs/Msg/ROSHeader.h"

#include "ROSTransformStamped.generated.h" 



/** @addtogroup {NameDoxygenMessageContainer}
  * @brief {NameDoxygenMessageContainer}
  *
  * @{
  */
USTRUCT(Blueprintable)
struct FROSTransformStamped
{
	GENERATED_BODY()

public:
	/**
	* @cond
	*/
	FROSTransformStamped()
	{

	};
	/**
	 * @endcond
	 */

    
	UPROPERTY(EditAnywhere)
	FROSHeader Header;
    
	UPROPERTY(EditAnywhere)
	FString ChildFrameId;
    
	UPROPERTY(EditAnywhere)
	FROSTransform Transform;
    

	/**
	 * @cond
	 */
	void DDSToUE (const geometry_msgs_msg_TransformStamped& InData) 
	{
		Header.DDSToUE(InData.header);
		ConvertUtils::DDSStringToUE( InData.child_frame_id, ChildFrameId);
		Transform.DDSToUE(InData.transform);
	};

	void UEToDDS (geometry_msgs_msg_TransformStamped& OutData) 
	{
		Header.UEToDDS(OutData.header);
		ConvertUtils::UEStringToDDS(ChildFrameId, OutData.child_frame_id );
		Transform.UEToDDS(OutData.transform);
	};
    
	/**
	 * @endcond
	 */
};
/** @} */
