/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSTransform.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSTransform.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Utils/ConvertUtils.h"


#include "geometry_msgs/msg/Transform.h"

#include "ROSTransform.generated.h" 





/** @addtogroup {NameDoxygenMessageContainer}
  * @brief {NameDoxygenMessageContainer}
  *
  * @{
  */
USTRUCT(Blueprintable)
struct FROSTransform
{
    GENERATED_BODY()

public:
    /**
    * @cond
    */
    FROSTransform()
    {

    };
    /**
     * @endcond
     */

    
    UPROPERTY(EditAnywhere) 
    FVector Translation;
    
    UPROPERTY(EditAnywhere)
    FQuat Rotation;
    

    /**
     * @cond
     */
    void DDSToUE (const geometry_msgs_msg_Transform& InData) 
    {
        ConvertUtils::DDSVectorToUE(InData.translation, Translation);
        ConvertUtils::DDSQuaternionToUE(InData.rotation, Rotation);
    };

    void UEToDDS (geometry_msgs_msg_Transform& OutData) 
    {
        ConvertUtils::UEVectorToDDS(Translation, OutData.translation);
        ConvertUtils::UEQuaternionToDDS(Rotation, OutData.rotation);
    };
    
    /**
     * @endcond
     */
};
/** @} */