/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSTransform.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSTransform.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Utils/ConvertUtils.h"


#include "geometry_msgs/msg/Transform.h"

#include "ROSTransform.generated.h" 





USTRUCT(Blueprintable)
struct FROSTransform
{
    GENERATED_BODY()

    FROSTransform()
    {

    };

    
    UPROPERTY(EditAnywhere)
    FVector Translation;
    
    UPROPERTY(EditAnywhere)
    FQuat Rotation;
    

    void DDSToUE(const geometry_msgs_msg_Transform& InData);
    void UEToDDS(geometry_msgs_msg_Transform& OutData);
};