/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSHeader.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSHeader.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 

#include "std_msgs/msg/Header.h"

#include "BuiltinInterfaces/Msg/ROSTime.h"

#include "ROSHeader.generated.h"

/** @addtogroup {NameDoxygenMessageContainer}
  * @brief {NameDoxygenMessageContainer}
  *
  * @{
  */
USTRUCT(Blueprintable)
struct FROSHeader
{
	GENERATED_BODY()

public:
	/**
	* @cond
	*/
	FROSHeader()
	{

	};
	/**
	 * @endcond
	 */

    
	UPROPERTY(EditAnywhere)
	FROSTime Stamp;
    
	UPROPERTY(EditAnywhere)
	FString FrameId;
    

	/**
	 * @cond
	 */
	void DDSToUE (const std_msgs_msg_Header& InData) 
	{
		Stamp.DDSToUE(InData.stamp);
		ConvertUtils::DDSStringToUE( InData.frame_id, FrameId);
	};

	void UEToDDS (std_msgs_msg_Header& OutData) 
	{
		Stamp.UEToDDS(OutData.stamp);
		ConvertUtils::UEStringToDDS(FrameId, OutData.frame_id );
	};
    
	/**
	 * @endcond
	 */
};
/** @} */