/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/BatteryState.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\BatteryState.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_BATTERYSTATE_H_509EC3D8BFC654250F8AB3AC5DD5E82D
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_BATTERYSTATE_H_509EC3D8BFC654250F8AB3AC5DD5E82D

#include "std_msgs\msg\Header.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_STATUS_UNKNOWN 0
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_STATUS_CHARGING 1
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_STATUS_DISCHARGING 2
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_STATUS_NOT_CHARGING 3
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_STATUS_FULL 4
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_HEALTH_UNKNOWN 0
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_HEALTH_GOOD 1
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_HEALTH_OVERHEAT 2
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_HEALTH_DEAD 3
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_HEALTH_OVERVOLTAGE 4
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_HEALTH_UNSPEC_FAILURE 5
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_HEALTH_COLD 6
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE 7
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE 8
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_TECHNOLOGY_UNKNOWN 0
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_TECHNOLOGY_NIMH 1
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_TECHNOLOGY_LION 2
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_TECHNOLOGY_LIPO 3
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_TECHNOLOGY_LIFE 4
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_TECHNOLOGY_NICD 5
#define sensor_msgs_msg_BatteryState_Constants_POWER_SUPPLY_TECHNOLOGY_LIMN 6
#ifndef DDS_SEQUENCE_FLOAT_DEFINED
#define DDS_SEQUENCE_FLOAT_DEFINED
typedef struct dds_sequence_float
{
  uint32_t _maximum;
  uint32_t _length;
  float *_buffer;
  bool _release;
} dds_sequence_float;

#define dds_sequence_float__alloc() \
((dds_sequence_float*) dds_alloc (sizeof (dds_sequence_float)));

#define dds_sequence_float_allocbuf(l) \
((float *) dds_alloc ((l) * sizeof (float)))
#endif /* DDS_SEQUENCE_FLOAT_DEFINED */

#ifndef DDS_SEQUENCE_FLOAT_DEFINED
#define DDS_SEQUENCE_FLOAT_DEFINED
typedef struct dds_sequence_float
{
  uint32_t _maximum;
  uint32_t _length;
  float *_buffer;
  bool _release;
} dds_sequence_float;

#define dds_sequence_float__alloc() \
((dds_sequence_float*) dds_alloc (sizeof (dds_sequence_float)));

#define dds_sequence_float_allocbuf(l) \
((float *) dds_alloc ((l) * sizeof (float)))
#endif /* DDS_SEQUENCE_FLOAT_DEFINED */

typedef struct sensor_msgs_msg_BatteryState
{
  struct std_msgs_msg_Header header;
  float voltage;
  float temperature;
  float current;
  float charge;
  float capacity;
  float design_capacity;
  float percentage;
  uint8_t power_supply_status;
  uint8_t power_supply_health;
  uint8_t power_supply_technology;
  bool present;
  dds_sequence_float cell_voltage;
  dds_sequence_float cell_temperature;
  char * location;
  char * serial_number;
} sensor_msgs_msg_BatteryState;

 extern const dds_topic_descriptor_t sensor_msgs_msg_BatteryState_desc;

#define sensor_msgs_msg_BatteryState__alloc() \
((sensor_msgs_msg_BatteryState*) dds_alloc (sizeof (sensor_msgs_msg_BatteryState)));

#define sensor_msgs_msg_BatteryState_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_BatteryState_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_BATTERYSTATE_H_509EC3D8BFC654250F8AB3AC5DD5E82D */
