/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/CameraInfo.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\CameraInfo.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "CameraInfo.h"

static const uint32_t sensor_msgs_msg_CameraInfo_ops [] =
{
  /* CameraInfo */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (sensor_msgs_msg_CameraInfo, header), (3u << 16u) + 28u /* Header */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_CameraInfo, height),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_CameraInfo, width),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (sensor_msgs_msg_CameraInfo, distortion_model),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_CameraInfo, d),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_CameraInfo, k), 9u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_CameraInfo, r), 9u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_CameraInfo, p), 12u,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_CameraInfo, binning_x),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_CameraInfo, binning_y),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (sensor_msgs_msg_CameraInfo, roi), (3u << 16u) + 15u /* RegionOfInterest */,
  DDS_OP_RTS,

  /* Header */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (std_msgs_msg_Header, frame_id),
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS,

  /* RegionOfInterest */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_RegionOfInterest, x_offset),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_RegionOfInterest, y_offset),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_RegionOfInterest, height),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_RegionOfInterest, width),
  DDS_OP_ADR | DDS_OP_TYPE_BLN, offsetof (sensor_msgs_msg_RegionOfInterest, do_rectify),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_CameraInfo_desc =
{
  .m_size = sizeof (sensor_msgs_msg_CameraInfo),
  .m_align = dds_alignof (sensor_msgs_msg_CameraInfo),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "sensor_msgs::msg::dds_::CameraInfo_",
  .m_keys = NULL,
  .m_nops = 24,
  .m_ops = sensor_msgs_msg_CameraInfo_ops,
  .m_meta = ""
};

