/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/CameraInfo.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\CameraInfo.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_CAMERAINFO_H_EBD257B57A9E00EC29F8F01BC7723C2B
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_CAMERAINFO_H_EBD257B57A9E00EC29F8F01BC7723C2B

#include "sensor_msgs\msg\RegionOfInterest.h"

#include "std_msgs\msg\Header.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef double sensor_msgs_msg_double__9[9];

#define sensor_msgs_msg_double__9__alloc() \
((sensor_msgs_msg_double__9*) dds_alloc (sizeof (sensor_msgs_msg_double__9)));

typedef double sensor_msgs_msg_double__12[12];

#define sensor_msgs_msg_double__12__alloc() \
((sensor_msgs_msg_double__12*) dds_alloc (sizeof (sensor_msgs_msg_double__12)));

#ifndef DDS_SEQUENCE_DOUBLE_DEFINED
#define DDS_SEQUENCE_DOUBLE_DEFINED
typedef struct dds_sequence_double
{
  uint32_t _maximum;
  uint32_t _length;
  double *_buffer;
  bool _release;
} dds_sequence_double;

#define dds_sequence_double__alloc() \
((dds_sequence_double*) dds_alloc (sizeof (dds_sequence_double)));

#define dds_sequence_double_allocbuf(l) \
((double *) dds_alloc ((l) * sizeof (double)))
#endif /* DDS_SEQUENCE_DOUBLE_DEFINED */

typedef struct sensor_msgs_msg_CameraInfo
{
  struct std_msgs_msg_Header header;
  uint32_t height;
  uint32_t width;
  char * distortion_model;
  dds_sequence_double d;
  sensor_msgs_msg_double__9 k;
  sensor_msgs_msg_double__9 r;
  sensor_msgs_msg_double__12 p;
  uint32_t binning_x;
  uint32_t binning_y;
  struct sensor_msgs_msg_RegionOfInterest roi;
} sensor_msgs_msg_CameraInfo;

 __declspec(dllimport) const dds_topic_descriptor_t sensor_msgs_msg_CameraInfo_desc;

#define sensor_msgs_msg_CameraInfo__alloc() \
((sensor_msgs_msg_CameraInfo*) dds_alloc (sizeof (sensor_msgs_msg_CameraInfo)));

#define sensor_msgs_msg_CameraInfo_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_CameraInfo_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_CAMERAINFO_H_EBD257B57A9E00EC29F8F01BC7723C2B */
