/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/ChannelFloat32.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\ChannelFloat32.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "ChannelFloat32.h"

static const uint32_t sensor_msgs_msg_ChannelFloat32_ops [] =
{
  /* ChannelFloat32 */
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (sensor_msgs_msg_ChannelFloat32, name),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_ChannelFloat32, values),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_ChannelFloat32_desc =
{
  .m_size = sizeof (sensor_msgs_msg_ChannelFloat32),
  .m_align = dds_alignof (sensor_msgs_msg_ChannelFloat32),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "sensor_msgs::msg::ChannelFloat32",
  .m_keys = NULL,
  .m_nops = 3,
  .m_ops = sensor_msgs_msg_ChannelFloat32_ops,
  .m_meta = ""
};

