/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/ChannelFloat32.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\ChannelFloat32.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_CHANNELFLOAT32_H_B2C59107038CAFE8A159F3525D45EFED
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_CHANNELFLOAT32_H_B2C59107038CAFE8A159F3525D45EFED

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_FLOAT_DEFINED
#define DDS_SEQUENCE_FLOAT_DEFINED
typedef struct dds_sequence_float
{
  uint32_t _maximum;
  uint32_t _length;
  float *_buffer;
  bool _release;
} dds_sequence_float;

#define dds_sequence_float__alloc() \
((dds_sequence_float*) dds_alloc (sizeof (dds_sequence_float)));

#define dds_sequence_float_allocbuf(l) \
((float *) dds_alloc ((l) * sizeof (float)))
#endif /* DDS_SEQUENCE_FLOAT_DEFINED */

typedef struct sensor_msgs_msg_ChannelFloat32
{
  char * name;
  dds_sequence_float values;
} sensor_msgs_msg_ChannelFloat32;

 extern const dds_topic_descriptor_t sensor_msgs_msg_ChannelFloat32_desc;

#define sensor_msgs_msg_ChannelFloat32__alloc() \
((sensor_msgs_msg_ChannelFloat32*) dds_alloc (sizeof (sensor_msgs_msg_ChannelFloat32)));

#define sensor_msgs_msg_ChannelFloat32_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_ChannelFloat32_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_CHANNELFLOAT32_H_B2C59107038CAFE8A159F3525D45EFED */
