/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/FluidPressure.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\FluidPressure.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_FLUIDPRESSURE_H_7B3B0C593F3DFFC9E30D53DD4CE13154
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_FLUIDPRESSURE_H_7B3B0C593F3DFFC9E30D53DD4CE13154

#include "std_msgs/msg/Header.h"

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct sensor_msgs_msg_FluidPressure
{
  struct std_msgs_msg_Header header;
  double fluid_pressure;
  double variance;
} sensor_msgs_msg_FluidPressure;

 extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t sensor_msgs_msg_FluidPressure_desc;

#define sensor_msgs_msg_FluidPressure__alloc() \
((sensor_msgs_msg_FluidPressure*) dds_alloc (sizeof (sensor_msgs_msg_FluidPressure)));

#define sensor_msgs_msg_FluidPressure_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_FluidPressure_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_FLUIDPRESSURE_H_7B3B0C593F3DFFC9E30D53DD4CE13154 */
