/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/FluidPressure.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\FluidPressure.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "FluidPressure.h"

static const uint32_t sensor_msgs_msg_FluidPressure_ops [] =
{
  /* FluidPressure */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (sensor_msgs_msg_FluidPressure, header), (3u << 16u) + 8u /* Header */,
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_FluidPressure, fluid_pressure),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_FluidPressure, variance),
  DDS_OP_RTS,

  /* Header */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (std_msgs_msg_Header, frame_id),
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_FluidPressure_desc =
{
  .m_size = sizeof (sensor_msgs_msg_FluidPressure),
  .m_align = dds_alignof (sensor_msgs_msg_FluidPressure),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "sensor_msgs::msg::FluidPressure",
  .m_keys = NULL,
  .m_nops = 10,
  .m_ops = sensor_msgs_msg_FluidPressure_ops,
  .m_meta = ""
};

