/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/Image.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\Image.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_IMAGE_H_2F215486BCF1AC805628C4457B1A0007
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_IMAGE_H_2F215486BCF1AC805628C4457B1A0007

#include "std_msgs/msg/Header.h"

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_UINT8_DEFINED
#define DDS_SEQUENCE_UINT8_DEFINED
typedef struct dds_sequence_uint8
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_uint8;

#define dds_sequence_uint8__alloc() \
((dds_sequence_uint8*) dds_alloc (sizeof (dds_sequence_uint8)));

#define dds_sequence_uint8_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_UINT8_DEFINED */

typedef struct sensor_msgs_msg_Image
{
  struct std_msgs_msg_Header header;
  uint32_t height;
  uint32_t width;
  char * encoding;
  uint8_t is_bigendian;
  uint32_t step;
  dds_sequence_uint8 data;
} sensor_msgs_msg_Image;

extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t sensor_msgs_msg_Image_desc;

#define sensor_msgs_msg_Image__alloc() \
((sensor_msgs_msg_Image*) dds_alloc (sizeof (sensor_msgs_msg_Image)));

#define sensor_msgs_msg_Image_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_Image_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_IMAGE_H_2F215486BCF1AC805628C4457B1A0007 */
