/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/Image.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\Image.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "Image.h"

static const uint32_t sensor_msgs_msg_Image_ops [] =
{
  /* Image */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (sensor_msgs_msg_Image, header), (3u << 16u) + 16u /* Header */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_Image, height),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_Image, width),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (sensor_msgs_msg_Image, encoding),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (sensor_msgs_msg_Image, is_bigendian),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_Image, step),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (sensor_msgs_msg_Image, data),
  DDS_OP_RTS,

  /* Header */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (std_msgs_msg_Header, frame_id),
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_Image_desc =
{
  .m_size = sizeof (sensor_msgs_msg_Image),
  .m_align = dds_alignof (sensor_msgs_msg_Image),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "sensor_msgs::msg::dds_::Image_",
  .m_keys = NULL,
  .m_nops = 14,
  .m_ops = sensor_msgs_msg_Image_ops,
  .m_meta = ""
};

