/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/Imu.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\Imu.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_IMU_H_173B5B8AE87D2DB60535168491962DC2
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_IMU_H_173B5B8AE87D2DB60535168491962DC2

#include "geometry_msgs\msg\Quaternion.h"

#include "geometry_msgs\msg\Vector3.h"

#include "std_msgs\msg\Header.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef double sensor_msgs_msg_double__9[9];

#define sensor_msgs_msg_double__9__alloc() \
((sensor_msgs_msg_double__9*) dds_alloc (sizeof (sensor_msgs_msg_double__9)));

typedef struct sensor_msgs_msg_Imu
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_Quaternion orientation;
  sensor_msgs_msg_double__9 orientation_covariance;
  struct geometry_msgs_msg_Vector3 angular_velocity;
  sensor_msgs_msg_double__9 angular_velocity_covariance;
  struct geometry_msgs_msg_Vector3 linear_acceleration;
  sensor_msgs_msg_double__9 linear_acceleration_covariance;
} sensor_msgs_msg_Imu;

 __declspec(dllimport) const dds_topic_descriptor_t sensor_msgs_msg_Imu_desc;

#define sensor_msgs_msg_Imu__alloc() \
((sensor_msgs_msg_Imu*) dds_alloc (sizeof (sensor_msgs_msg_Imu)));

#define sensor_msgs_msg_Imu_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_Imu_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_IMU_H_173B5B8AE87D2DB60535168491962DC2 */
