/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/JoyFeedbackArray.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\JoyFeedbackArray.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "JoyFeedbackArray.h"

static const uint32_t sensor_msgs_msg_JoyFeedbackArray_ops [] =
{
  /* JoyFeedbackArray */
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (sensor_msgs_msg_JoyFeedbackArray, array), sizeof (sensor_msgs_msg_JoyFeedback), (4u << 16u) + 5u /* JoyFeedback */,
  DDS_OP_RTS,

  /* JoyFeedback */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (sensor_msgs_msg_JoyFeedback, type),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (sensor_msgs_msg_JoyFeedback, id),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_JoyFeedback, intensity),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_JoyFeedbackArray_desc =
{
  .m_size = sizeof (sensor_msgs_msg_JoyFeedbackArray),
  .m_align = dds_alignof (sensor_msgs_msg_JoyFeedbackArray),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "sensor_msgs::msg::JoyFeedbackArray",
  .m_keys = NULL,
  .m_nops = 6,
  .m_ops = sensor_msgs_msg_JoyFeedbackArray_ops,
  .m_meta = ""
};

