/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/JoyFeedback.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\JoyFeedback.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "JoyFeedback.h"

static const uint32_t sensor_msgs_msg_JoyFeedback_ops [] =
{
  /* JoyFeedback */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (sensor_msgs_msg_JoyFeedback, type),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (sensor_msgs_msg_JoyFeedback, id),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_JoyFeedback, intensity),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_JoyFeedback_desc =
{
  .m_size = sizeof (sensor_msgs_msg_JoyFeedback),
  .m_align = dds_alignof (sensor_msgs_msg_JoyFeedback),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "sensor_msgs::msg::JoyFeedback",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = sensor_msgs_msg_JoyFeedback_ops,
  .m_meta = ""
};

