/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/JoyFeedback.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\JoyFeedback.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_JOYFEEDBACK_H_13BFCA442351C350FF5BDDDF7453967A
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_JOYFEEDBACK_H_13BFCA442351C350FF5BDDDF7453967A

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define sensor_msgs_msg_JoyFeedback_Constants_TYPE_LED 0
#define sensor_msgs_msg_JoyFeedback_Constants_TYPE_RUMBLE 1
#define sensor_msgs_msg_JoyFeedback_Constants_TYPE_BUZZER 2
typedef struct sensor_msgs_msg_JoyFeedback
{
  uint8_t type;
  uint8_t id;
  float intensity;
} sensor_msgs_msg_JoyFeedback;

 extern const dds_topic_descriptor_t sensor_msgs_msg_JoyFeedback_desc;

#define sensor_msgs_msg_JoyFeedback__alloc() \
((sensor_msgs_msg_JoyFeedback*) dds_alloc (sizeof (sensor_msgs_msg_JoyFeedback)));

#define sensor_msgs_msg_JoyFeedback_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_JoyFeedback_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_JOYFEEDBACK_H_13BFCA442351C350FF5BDDDF7453967A */
