/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/LaserEcho.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\LaserEcho.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "LaserEcho.h"

static const uint32_t sensor_msgs_msg_LaserEcho_ops [] =
{
  /* LaserEcho */
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_LaserEcho, echoes),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_LaserEcho_desc =
{
  .m_size = sizeof (sensor_msgs_msg_LaserEcho),
  .m_align = dds_alignof (sensor_msgs_msg_LaserEcho),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "sensor_msgs::msg::LaserEcho",
  .m_keys = NULL,
  .m_nops = 2,
  .m_ops = sensor_msgs_msg_LaserEcho_ops,
  .m_meta = ""
};

