/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/LaserScan.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\LaserScan.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_LASERSCAN_H_E396891CC3090A7ABBAB81878303D3E3
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_LASERSCAN_H_E396891CC3090A7ABBAB81878303D3E3

#include "std_msgs\msg\Header.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_FLOAT_DEFINED
#define DDS_SEQUENCE_FLOAT_DEFINED
typedef struct dds_sequence_float
{
  uint32_t _maximum;
  uint32_t _length;
  float *_buffer;
  bool _release;
} dds_sequence_float;

#define dds_sequence_float__alloc() \
((dds_sequence_float*) dds_alloc (sizeof (dds_sequence_float)));

#define dds_sequence_float_allocbuf(l) \
((float *) dds_alloc ((l) * sizeof (float)))
#endif /* DDS_SEQUENCE_FLOAT_DEFINED */

#ifndef DDS_SEQUENCE_FLOAT_DEFINED
#define DDS_SEQUENCE_FLOAT_DEFINED
typedef struct dds_sequence_float
{
  uint32_t _maximum;
  uint32_t _length;
  float *_buffer;
  bool _release;
} dds_sequence_float;

#define dds_sequence_float__alloc() \
((dds_sequence_float*) dds_alloc (sizeof (dds_sequence_float)));

#define dds_sequence_float_allocbuf(l) \
((float *) dds_alloc ((l) * sizeof (float)))
#endif /* DDS_SEQUENCE_FLOAT_DEFINED */

typedef struct sensor_msgs_msg_LaserScan
{
  struct std_msgs_msg_Header header;
  float angle_min;
  float angle_max;
  float angle_increment;
  float time_increment;
  float scan_time;
  float range_min;
  float range_max;
  dds_sequence_float ranges;
  dds_sequence_float intensities;
} sensor_msgs_msg_LaserScan;

  __declspec(dllimport) const dds_topic_descriptor_t sensor_msgs_msg_LaserScan_desc;

#define sensor_msgs_msg_LaserScan__alloc() \
((sensor_msgs_msg_LaserScan*) dds_alloc (sizeof (sensor_msgs_msg_LaserScan)));

#define sensor_msgs_msg_LaserScan_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_LaserScan_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_LASERSCAN_H_E396891CC3090A7ABBAB81878303D3E3 */
