/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/LaserEcho.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\LaserEcho.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_LASERECHO_H_1DE9C3F1FDCD33CA4FA1247FC342A3B4
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_LASERECHO_H_1DE9C3F1FDCD33CA4FA1247FC342A3B4

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_FLOAT_DEFINED
#define DDS_SEQUENCE_FLOAT_DEFINED
typedef struct dds_sequence_float
{
  uint32_t _maximum;
  uint32_t _length;
  float *_buffer;
  bool _release;
} dds_sequence_float;

#define dds_sequence_float__alloc() \
((dds_sequence_float*) dds_alloc (sizeof (dds_sequence_float)));

#define dds_sequence_float_allocbuf(l) \
((float *) dds_alloc ((l) * sizeof (float)))
#endif /* DDS_SEQUENCE_FLOAT_DEFINED */

typedef struct sensor_msgs_msg_LaserEcho
{
  dds_sequence_float echoes;
} sensor_msgs_msg_LaserEcho;

 extern const dds_topic_descriptor_t sensor_msgs_msg_LaserEcho_desc;

#define sensor_msgs_msg_LaserEcho__alloc() \
((sensor_msgs_msg_LaserEcho*) dds_alloc (sizeof (sensor_msgs_msg_LaserEcho)));

#define sensor_msgs_msg_LaserEcho_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_LaserEcho_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_LASERECHO_H_1DE9C3F1FDCD33CA4FA1247FC342A3B4 */
