/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/MagneticField.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\MagneticField.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "MagneticField.h"

static const uint32_t sensor_msgs_msg_MagneticField_ops [] =
{
  /* MagneticField */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (sensor_msgs_msg_MagneticField, header), (3u << 16u) + 10u /* Header */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (sensor_msgs_msg_MagneticField, magnetic_field), (3u << 16u) + 18u /* Vector3 */,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_MagneticField, magnetic_field_covariance), 9u,
  DDS_OP_RTS,

  /* Header */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (std_msgs_msg_Header, frame_id),
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS,

  /* Vector3 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_MagneticField_desc =
{
  .m_size = sizeof (sensor_msgs_msg_MagneticField),
  .m_align = dds_alignof (sensor_msgs_msg_MagneticField),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "sensor_msgs::msg::MagneticField",
  .m_keys = NULL,
  .m_nops = 14,
  .m_ops = sensor_msgs_msg_MagneticField_ops,
  .m_meta = ""
};

