/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/MagneticField.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\MagneticField.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_MAGNETICFIELD_H_1DBE7CFD3FFF35B01DFEC578635AE68A
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_MAGNETICFIELD_H_1DBE7CFD3FFF35B01DFEC578635AE68A

#include "geometry_msgs/msg/Vector3.h"

#include "std_msgs/msg/Header.h"

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef double sensor_msgs_msg_double__9[9];

#define sensor_msgs_msg_double__9__alloc() \
((sensor_msgs_msg_double__9*) dds_alloc (sizeof (sensor_msgs_msg_double__9)));

typedef struct sensor_msgs_msg_MagneticField
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_Vector3 magnetic_field;
  sensor_msgs_msg_double__9 magnetic_field_covariance;
} sensor_msgs_msg_MagneticField;

 extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t sensor_msgs_msg_MagneticField_desc;

#define sensor_msgs_msg_MagneticField__alloc() \
((sensor_msgs_msg_MagneticField*) dds_alloc (sizeof (sensor_msgs_msg_MagneticField)));

#define sensor_msgs_msg_MagneticField_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_MagneticField_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_MAGNETICFIELD_H_1DBE7CFD3FFF35B01DFEC578635AE68A */
