/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/MultiEchoLaserScan.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\MultiEchoLaserScan.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_MULTIECHOLASERSCAN_H_3FF4787EC04E6B1217FDBBDD57BC9375
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_MULTIECHOLASERSCAN_H_3FF4787EC04E6B1217FDBBDD57BC9375

#include "sensor_msgs/msg/LaserEcho.h"

#include "std_msgs/msg/Header.h"

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_SENSOR_MSGS_MSG_LASERECHO_DEFINED
#define DDS_SEQUENCE_SENSOR_MSGS_MSG_LASERECHO_DEFINED
typedef struct dds_sequence_sensor_msgs_msg_LaserEcho
{
  uint32_t _maximum;
  uint32_t _length;
  struct sensor_msgs_msg_LaserEcho *_buffer;
  bool _release;
} dds_sequence_sensor_msgs_msg_LaserEcho;

#define dds_sequence_sensor_msgs_msg_LaserEcho__alloc() \
((dds_sequence_sensor_msgs_msg_LaserEcho*) dds_alloc (sizeof (dds_sequence_sensor_msgs_msg_LaserEcho)));

#define dds_sequence_sensor_msgs_msg_LaserEcho_allocbuf(l) \
((struct sensor_msgs_msg_LaserEcho *) dds_alloc ((l) * sizeof (struct sensor_msgs_msg_LaserEcho)))
#endif /* DDS_SEQUENCE_SENSOR_MSGS_MSG_LASERECHO_DEFINED */

#ifndef DDS_SEQUENCE_SENSOR_MSGS_MSG_LASERECHO_DEFINED
#define DDS_SEQUENCE_SENSOR_MSGS_MSG_LASERECHO_DEFINED
typedef struct dds_sequence_sensor_msgs_msg_LaserEcho
{
  uint32_t _maximum;
  uint32_t _length;
  struct sensor_msgs_msg_LaserEcho *_buffer;
  bool _release;
} dds_sequence_sensor_msgs_msg_LaserEcho;

#define dds_sequence_sensor_msgs_msg_LaserEcho__alloc() \
((dds_sequence_sensor_msgs_msg_LaserEcho*) dds_alloc (sizeof (dds_sequence_sensor_msgs_msg_LaserEcho)));

#define dds_sequence_sensor_msgs_msg_LaserEcho_allocbuf(l) \
((struct sensor_msgs_msg_LaserEcho *) dds_alloc ((l) * sizeof (struct sensor_msgs_msg_LaserEcho)))
#endif /* DDS_SEQUENCE_SENSOR_MSGS_MSG_LASERECHO_DEFINED */

typedef struct sensor_msgs_msg_MultiEchoLaserScan
{
  struct std_msgs_msg_Header header;
  float angle_min;
  float angle_max;
  float angle_increment;
  float time_increment;
  float scan_time;
  float range_min;
  float range_max;
  dds_sequence_sensor_msgs_msg_LaserEcho ranges;
  dds_sequence_sensor_msgs_msg_LaserEcho intensities;
} sensor_msgs_msg_MultiEchoLaserScan;

 extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t sensor_msgs_msg_MultiEchoLaserScan_desc;

#define sensor_msgs_msg_MultiEchoLaserScan__alloc() \
((sensor_msgs_msg_MultiEchoLaserScan*) dds_alloc (sizeof (sensor_msgs_msg_MultiEchoLaserScan)));

#define sensor_msgs_msg_MultiEchoLaserScan_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_MultiEchoLaserScan_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_MULTIECHOLASERSCAN_H_3FF4787EC04E6B1217FDBBDD57BC9375 */
