/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/MultiEchoLaserScan.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\MultiEchoLaserScan.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "MultiEchoLaserScan.h"

static const uint32_t sensor_msgs_msg_MultiEchoLaserScan_ops [] =
{
  /* MultiEchoLaserScan */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (sensor_msgs_msg_MultiEchoLaserScan, header), (3u << 16u) + 26u /* Header */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_MultiEchoLaserScan, angle_min),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_MultiEchoLaserScan, angle_max),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_MultiEchoLaserScan, angle_increment),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_MultiEchoLaserScan, time_increment),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_MultiEchoLaserScan, scan_time),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_MultiEchoLaserScan, range_min),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_MultiEchoLaserScan, range_max),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (sensor_msgs_msg_MultiEchoLaserScan, ranges), sizeof (sensor_msgs_msg_LaserEcho), (4u << 16u) + 20u /* LaserEcho */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (sensor_msgs_msg_MultiEchoLaserScan, intensities), sizeof (sensor_msgs_msg_LaserEcho), (4u << 16u) + 16u /* LaserEcho */,
  DDS_OP_RTS,

  /* Header */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (std_msgs_msg_Header, frame_id),
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS,

  /* LaserEcho */
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_LaserEcho, echoes),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_MultiEchoLaserScan_desc =
{
  .m_size = sizeof (sensor_msgs_msg_MultiEchoLaserScan),
  .m_align = dds_alignof (sensor_msgs_msg_MultiEchoLaserScan),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "sensor_msgs::msg::MultiEchoLaserScan",
  .m_keys = NULL,
  .m_nops = 19,
  .m_ops = sensor_msgs_msg_MultiEchoLaserScan_ops,
  .m_meta = ""
};

