/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/NavSatFix.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\NavSatFix.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "NavSatFix.h"

static const uint32_t sensor_msgs_msg_NavSatFix_ops [] =
{
  /* NavSatFix */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (sensor_msgs_msg_NavSatFix, header), (3u << 16u) + 18u /* Header */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (sensor_msgs_msg_NavSatFix, status), (3u << 16u) + 26u /* NavSatStatus */,
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_NavSatFix, latitude),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_NavSatFix, longitude),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_NavSatFix, altitude),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_NavSatFix, position_covariance), 9u,
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (sensor_msgs_msg_NavSatFix, position_covariance_type),
  DDS_OP_RTS,

  /* Header */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (std_msgs_msg_Header, frame_id),
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS,

  /* NavSatStatus */
  DDS_OP_ADR | DDS_OP_TYPE_1BY | DDS_OP_FLAG_SGN, offsetof (sensor_msgs_msg_NavSatStatus, status),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (sensor_msgs_msg_NavSatStatus, service),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_NavSatFix_desc =
{
  .m_size = sizeof (sensor_msgs_msg_NavSatFix),
  .m_align = dds_alignof (sensor_msgs_msg_NavSatFix),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "sensor_msgs::msg::NavSatFix",
  .m_keys = NULL,
  .m_nops = 17,
  .m_ops = sensor_msgs_msg_NavSatFix_ops,
  .m_meta = ""
};

