/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/NavSatFix.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\NavSatFix.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_NAVSATFIX_H_F0C32DB80CE320C5C894B79323472646
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_NAVSATFIX_H_F0C32DB80CE320C5C894B79323472646

#include "sensor_msgs\msg\NavSatStatus.h"

#include "std_msgs\msg\Header.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef double sensor_msgs_msg_double__9[9];

#define sensor_msgs_msg_double__9__alloc() \
((sensor_msgs_msg_double__9*) dds_alloc (sizeof (sensor_msgs_msg_double__9)));

#define sensor_msgs_msg_NavSatFix_Constants_COVARIANCE_TYPE_UNKNOWN 0
#define sensor_msgs_msg_NavSatFix_Constants_COVARIANCE_TYPE_APPROXIMATED 1
#define sensor_msgs_msg_NavSatFix_Constants_COVARIANCE_TYPE_DIAGONAL_KNOWN 2
#define sensor_msgs_msg_NavSatFix_Constants_COVARIANCE_TYPE_KNOWN 3
typedef struct sensor_msgs_msg_NavSatFix
{
  struct std_msgs_msg_Header header;
  struct sensor_msgs_msg_NavSatStatus status;
  double latitude;
  double longitude;
  double altitude;
  sensor_msgs_msg_double__9 position_covariance;
  uint8_t position_covariance_type;
} sensor_msgs_msg_NavSatFix;

  __declspec(dllimport) const dds_topic_descriptor_t sensor_msgs_msg_NavSatFix_desc;

#define sensor_msgs_msg_NavSatFix__alloc() \
((sensor_msgs_msg_NavSatFix*) dds_alloc (sizeof (sensor_msgs_msg_NavSatFix)));

#define sensor_msgs_msg_NavSatFix_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_NavSatFix_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_NAVSATFIX_H_F0C32DB80CE320C5C894B79323472646 */
