/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/NavSatStatus.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\NavSatStatus.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_NAVSATSTATUS_H_951E2623D49E5C18EEE04EBB43747BA1
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_NAVSATSTATUS_H_951E2623D49E5C18EEE04EBB43747BA1

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define sensor_msgs_msg_NavSatStatus_Constants_STATUS_NO_FIX -1
#define sensor_msgs_msg_NavSatStatus_Constants_STATUS_FIX 0
#define sensor_msgs_msg_NavSatStatus_Constants_STATUS_SBAS_FIX 1
#define sensor_msgs_msg_NavSatStatus_Constants_STATUS_GBAS_FIX 2
#define sensor_msgs_msg_NavSatStatus_Constants_SERVICE_GPS 1
#define sensor_msgs_msg_NavSatStatus_Constants_SERVICE_GLONASS 2
#define sensor_msgs_msg_NavSatStatus_Constants_SERVICE_COMPASS 4
#define sensor_msgs_msg_NavSatStatus_Constants_SERVICE_GALILEO 8
typedef struct sensor_msgs_msg_NavSatStatus
{
  int8_t status;
  uint16_t service;
} sensor_msgs_msg_NavSatStatus;

   __declspec(dllimport) const dds_topic_descriptor_t sensor_msgs_msg_NavSatStatus_desc;

#define sensor_msgs_msg_NavSatStatus__alloc() \
((sensor_msgs_msg_NavSatStatus*) dds_alloc (sizeof (sensor_msgs_msg_NavSatStatus)));

#define sensor_msgs_msg_NavSatStatus_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_NavSatStatus_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_NAVSATSTATUS_H_951E2623D49E5C18EEE04EBB43747BA1 */
