/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/NavSatStatus.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\NavSatStatus.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "NavSatStatus.h"

static const uint32_t sensor_msgs_msg_NavSatStatus_ops [] =
{
  /* NavSatStatus */
  DDS_OP_ADR | DDS_OP_TYPE_1BY | DDS_OP_FLAG_SGN, offsetof (sensor_msgs_msg_NavSatStatus, status),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (sensor_msgs_msg_NavSatStatus, service),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_NavSatStatus_desc =
{
  .m_size = sizeof (sensor_msgs_msg_NavSatStatus),
  .m_align = dds_alignof (sensor_msgs_msg_NavSatStatus),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "sensor_msgs::msg::NavSatStatus",
  .m_keys = NULL,
  .m_nops = 3,
  .m_ops = sensor_msgs_msg_NavSatStatus_ops,
  .m_meta = ""
};

