/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/PointField.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\PointField.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_POINTFIELD_H_1CF44C0FB0CB64D5FBF2672B80A547E6
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_POINTFIELD_H_1CF44C0FB0CB64D5FBF2672B80A547E6

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct sensor_msgs_msg_PointField
{
  char * name;
  uint32_t offset;
  uint8_t datatype;
  uint32_t count;
} sensor_msgs_msg_PointField;

__declspec(dllimport) const dds_topic_descriptor_t sensor_msgs_msg_PointField_desc;

#define sensor_msgs_msg_PointField__alloc() \
((sensor_msgs_msg_PointField*) dds_alloc (sizeof (sensor_msgs_msg_PointField)));

#define sensor_msgs_msg_PointField_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_PointField_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_POINTFIELD_H_1CF44C0FB0CB64D5FBF2672B80A547E6 */
