/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/PointCloud2.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\PointCloud2.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "PointCloud2.h"

static const uint32_t sensor_msgs_msg_PointCloud2_ops [] =
{
  /* PointCloud2 */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (sensor_msgs_msg_PointCloud2, header), (3u << 16u) + 22u /* Header */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_PointCloud2, height),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_PointCloud2, width),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (sensor_msgs_msg_PointCloud2, fields), sizeof (sensor_msgs_msg_PointField), (4u << 16u) + 26u /* PointField */,
  DDS_OP_ADR | DDS_OP_TYPE_BLN, offsetof (sensor_msgs_msg_PointCloud2, is_bigendian),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_PointCloud2, point_step),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_PointCloud2, row_step),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (sensor_msgs_msg_PointCloud2, data),
  DDS_OP_ADR | DDS_OP_TYPE_BLN, offsetof (sensor_msgs_msg_PointCloud2, is_dense),
  DDS_OP_RTS,

  /* Header */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (std_msgs_msg_Header, frame_id),
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS,

  /* PointField */
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (sensor_msgs_msg_PointField, name),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_PointField, offset),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (sensor_msgs_msg_PointField, datatype),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_PointField, count),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_PointCloud2_desc =
{
  .m_size = sizeof (sensor_msgs_msg_PointCloud2),
  .m_align = dds_alignof (sensor_msgs_msg_PointCloud2),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "sensor_msgs::msg::dds_::PointCloud2_",
  .m_keys = NULL,
  .m_nops = 21,
  .m_ops = sensor_msgs_msg_PointCloud2_ops,
  .m_meta = ""
};

