/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/PointCloud2.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\PointCloud2.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_POINTCLOUD2_H_2EE9C9E915E75D4CABDD5FA37C6BF7D3
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_POINTCLOUD2_H_2EE9C9E915E75D4CABDD5FA37C6BF7D3

#include "sensor_msgs\msg\PointField.h"

#include "std_msgs\msg\Header.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_SENSOR_MSGS_MSG_POINTFIELD_DEFINED
#define DDS_SEQUENCE_SENSOR_MSGS_MSG_POINTFIELD_DEFINED
typedef struct dds_sequence_sensor_msgs_msg_PointField
{
  uint32_t _maximum;
  uint32_t _length;
  struct sensor_msgs_msg_PointField *_buffer;
  bool _release;
} dds_sequence_sensor_msgs_msg_PointField;

#define dds_sequence_sensor_msgs_msg_PointField__alloc() \
((dds_sequence_sensor_msgs_msg_PointField*) dds_alloc (sizeof (dds_sequence_sensor_msgs_msg_PointField)));

#define dds_sequence_sensor_msgs_msg_PointField_allocbuf(l) \
((struct sensor_msgs_msg_PointField *) dds_alloc ((l) * sizeof (struct sensor_msgs_msg_PointField)))
#endif /* DDS_SEQUENCE_SENSOR_MSGS_MSG_POINTFIELD_DEFINED */

#ifndef DDS_SEQUENCE_UINT8_DEFINED
#define DDS_SEQUENCE_UINT8_DEFINED
typedef struct dds_sequence_uint8
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_uint8;

#define dds_sequence_uint8__alloc() \
((dds_sequence_uint8*) dds_alloc (sizeof (dds_sequence_uint8)));

#define dds_sequence_uint8_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_UINT8_DEFINED */

typedef struct sensor_msgs_msg_PointCloud2
{
  struct std_msgs_msg_Header header;
  uint32_t height;
  uint32_t width;
  dds_sequence_sensor_msgs_msg_PointField fields;
  bool is_bigendian;
  uint32_t point_step;
  uint32_t row_step;
  dds_sequence_uint8 data;
  bool is_dense;
} sensor_msgs_msg_PointCloud2;

__declspec(dllimport) const dds_topic_descriptor_t sensor_msgs_msg_PointCloud2_desc;

#define sensor_msgs_msg_PointCloud2__alloc() \
((sensor_msgs_msg_PointCloud2*) dds_alloc (sizeof (sensor_msgs_msg_PointCloud2)));

#define sensor_msgs_msg_PointCloud2_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_PointCloud2_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_POINTCLOUD2_H_2EE9C9E915E75D4CABDD5FA37C6BF7D3 */
