/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/PointCloud.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\PointCloud.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "PointCloud.h"

static const uint32_t sensor_msgs_msg_PointCloud_ops [] =
{
  /* PointCloud */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (sensor_msgs_msg_PointCloud, header), (3u << 16u) + 12u /* Header */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (sensor_msgs_msg_PointCloud, points), sizeof (geometry_msgs_msg_Point32), (4u << 16u) + 20u /* Point32 */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (sensor_msgs_msg_PointCloud, channels), sizeof (sensor_msgs_msg_ChannelFloat32), (4u << 16u) + 23u /* ChannelFloat32 */,
  DDS_OP_RTS,

  /* Header */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (std_msgs_msg_Header, frame_id),
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS,

  /* Point32 */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point32, x),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point32, y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point32, z),
  DDS_OP_RTS,

  /* ChannelFloat32 */
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (sensor_msgs_msg_ChannelFloat32, name),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (sensor_msgs_msg_ChannelFloat32, values),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_PointCloud_desc =
{
  .m_size = sizeof (sensor_msgs_msg_PointCloud),
  .m_align = dds_alignof (sensor_msgs_msg_PointCloud),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "sensor_msgs::msg::PointCloud",
  .m_keys = NULL,
  .m_nops = 17,
  .m_ops = sensor_msgs_msg_PointCloud_ops,
  .m_meta = ""
};

