/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/PointField.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\PointField.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "PointField.h"

static const uint32_t sensor_msgs_msg_PointField_ops [] =
{
  /* PointField */
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (sensor_msgs_msg_PointField, name),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_PointField, offset),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (sensor_msgs_msg_PointField, datatype),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (sensor_msgs_msg_PointField, count),
  DDS_OP_RTS
};

const dds_topic_descriptor_t sensor_msgs_msg_PointField_desc =
{
  .m_size = sizeof (sensor_msgs_msg_PointField),
  .m_align = dds_alignof (sensor_msgs_msg_PointField),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "sensor_msgs::msg::PointField",
  .m_keys = NULL,
  .m_nops = 5,
  .m_ops = sensor_msgs_msg_PointField_ops,
  .m_meta = ""
};

