/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/sensor_msgs\msg/PointCloud.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\sensor_msgs\msg\PointCloud.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_POINTCLOUD_H_5D923FA8CDAC1BB5E7075646E4801820
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_POINTCLOUD_H_5D923FA8CDAC1BB5E7075646E4801820

#include "geometry_msgs\msg\Point32.h"

#include "sensor_msgs\msg\ChannelFloat32.h"

#include "std_msgs\msg\Header.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_GEOMETRY_MSGS_MSG_POINT32_DEFINED
#define DDS_SEQUENCE_GEOMETRY_MSGS_MSG_POINT32_DEFINED
typedef struct dds_sequence_geometry_msgs_msg_Point32
{
  uint32_t _maximum;
  uint32_t _length;
  struct geometry_msgs_msg_Point32 *_buffer;
  bool _release;
} dds_sequence_geometry_msgs_msg_Point32;

#define dds_sequence_geometry_msgs_msg_Point32__alloc() \
((dds_sequence_geometry_msgs_msg_Point32*) dds_alloc (sizeof (dds_sequence_geometry_msgs_msg_Point32)));

#define dds_sequence_geometry_msgs_msg_Point32_allocbuf(l) \
((struct geometry_msgs_msg_Point32 *) dds_alloc ((l) * sizeof (struct geometry_msgs_msg_Point32)))
#endif /* DDS_SEQUENCE_GEOMETRY_MSGS_MSG_POINT32_DEFINED */

#ifndef DDS_SEQUENCE_SENSOR_MSGS_MSG_CHANNELFLOAT32_DEFINED
#define DDS_SEQUENCE_SENSOR_MSGS_MSG_CHANNELFLOAT32_DEFINED
typedef struct dds_sequence_sensor_msgs_msg_ChannelFloat32
{
  uint32_t _maximum;
  uint32_t _length;
  struct sensor_msgs_msg_ChannelFloat32 *_buffer;
  bool _release;
} dds_sequence_sensor_msgs_msg_ChannelFloat32;

#define dds_sequence_sensor_msgs_msg_ChannelFloat32__alloc() \
((dds_sequence_sensor_msgs_msg_ChannelFloat32*) dds_alloc (sizeof (dds_sequence_sensor_msgs_msg_ChannelFloat32)));

#define dds_sequence_sensor_msgs_msg_ChannelFloat32_allocbuf(l) \
((struct sensor_msgs_msg_ChannelFloat32 *) dds_alloc ((l) * sizeof (struct sensor_msgs_msg_ChannelFloat32)))
#endif /* DDS_SEQUENCE_SENSOR_MSGS_MSG_CHANNELFLOAT32_DEFINED */

typedef struct sensor_msgs_msg_PointCloud
{
  struct std_msgs_msg_Header header;
  dds_sequence_geometry_msgs_msg_Point32 points;
  dds_sequence_sensor_msgs_msg_ChannelFloat32 channels;
} sensor_msgs_msg_PointCloud;

__declspec(dllimport) const dds_topic_descriptor_t sensor_msgs_msg_PointCloud_desc;

#define sensor_msgs_msg_PointCloud__alloc() \
((sensor_msgs_msg_PointCloud*) dds_alloc (sizeof (sensor_msgs_msg_PointCloud)));

#define sensor_msgs_msg_PointCloud_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_PointCloud_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_SENSOR_MSGS_MSG_POINTCLOUD_H_5D923FA8CDAC1BB5E7075646E4801820 */
