/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSClock.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSClock.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"

#include "rosgraph_msgs/msg/Clock.h"

#include "BuiltinInterfaces/Msg/ROSTime.h"

#include "ROSClock.generated.h" 





/** @addtogroup {NameDoxygenMessageContainer}
  * @brief {NameDoxygenMessageContainer}
  *
  * @{
  */
USTRUCT(Blueprintable)
struct FROSClock
{
    GENERATED_BODY()

public:
    /**
    * @cond
    */
    FROSClock()
    {

    };
    /**
     * @endcond
     */

    
    UPROPERTY(EditAnywhere)
    FROSTime Clock;
    

    /**
     * @cond
     */
    void DDSToUE (const rosgraph_msgs_msg_Clock& InData) 
    {
        Clock.DDSToUE(InData.clock);
    };

    void UEToDDS (rosgraph_msgs_msg_Clock& OutData) 
    {
        Clock.UEToDDS(OutData.clock);
    };
    
    /**
     * @endcond
     */
};
/** @} */



DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSClockCallback, const FROSClock, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UClock_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

public:

    UPROPERTY(BlueprintAssignable)
    FROSClockCallback OnDataChanged;

    virtual void Initialize() override {
        Data = rosgraph_msgs_msg_Clock__alloc();
    };

    virtual void Terminate() override {
        rosgraph_msgs_msg_Clock_free(Data, DDS_FREE_ALL);
    };

    UFUNCTION(BlueprintCallable)
    void GetData(FROSClock& Output)
    {
        Output.DDSToUE(*Data);
    };

    UFUNCTION(BlueprintCallable)
    void SetData(FROSClock Input)
    {
        Input.UEToDDS(*Data);
    };

    virtual void ExecuteMessageCallback() override
    {
        FROSClock NewData;
        NewData.DDSToUE(*Data);
        OnDataChanged.Broadcast(NewData);
    };

    virtual void* Get() override
    {
        return Data;
    };

    virtual const dds_topic_descriptor_t* GetTypeDesc() override
    {
        return &rosgraph_msgs_msg_Clock_desc;
    };

private:
    rosgraph_msgs_msg_Clock* Data;
};