/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Accel.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Accel.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_ACCEL_H_40C262EF49B2DE9B22F147C6934C97F1
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_ACCEL_H_40C262EF49B2DE9B22F147C6934C97F1

#include "geometry_msgs/msg/Vector3.h"

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Accel
{
  struct geometry_msgs_msg_Vector3 linear;
  struct geometry_msgs_msg_Vector3 angular;
} geometry_msgs_msg_Accel;

 extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t geometry_msgs_msg_Accel_desc;

#define geometry_msgs_msg_Accel__alloc() \
((geometry_msgs_msg_Accel*) dds_alloc (sizeof (geometry_msgs_msg_Accel)));

#define geometry_msgs_msg_Accel_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Accel_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_ACCEL_H_40C262EF49B2DE9B22F147C6934C97F1 */
