/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Accel.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Accel.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "Accel.h"

static const uint32_t geometry_msgs_msg_Accel_ops [] =
{
  /* Accel */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Accel, linear), (3u << 16u) + 7u /* Vector3 */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Accel, angular), (3u << 16u) + 4u /* Vector3 */,
  DDS_OP_RTS,

  /* Vector3 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_Accel_desc =
{
  .m_size = sizeof (geometry_msgs_msg_Accel),
  .m_align = dds_alignof (geometry_msgs_msg_Accel),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "geometry_msgs::msg::Accel",
  .m_keys = NULL,
  .m_nops = 7,
  .m_ops = geometry_msgs_msg_Accel_ops,
  .m_meta = ""
};

