/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Inertia.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Inertia.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_INERTIA_H_C5CC1C0F0B2CD637A8D7B96EF6DE28D1
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_INERTIA_H_C5CC1C0F0B2CD637A8D7B96EF6DE28D1

#include "geometry_msgs/msg/Vector3.h"

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"


#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Inertia
{
  double m;
  struct geometry_msgs_msg_Vector3 com;
  double ixx;
  double ixy;
  double ixz;
  double iyy;
  double iyz;
  double izz;
} geometry_msgs_msg_Inertia;

 extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t geometry_msgs_msg_Inertia_desc;

#define geometry_msgs_msg_Inertia__alloc() \
((geometry_msgs_msg_Inertia*) dds_alloc (sizeof (geometry_msgs_msg_Inertia)));

#define geometry_msgs_msg_Inertia_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Inertia_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_INERTIA_H_C5CC1C0F0B2CD637A8D7B96EF6DE28D1 */
