/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/InertiaStamped.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\InertiaStamped.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_INERTIASTAMPED_H_A755285C0F43AA37DD2BDA7BFB2539C0
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_INERTIASTAMPED_H_A755285C0F43AA37DD2BDA7BFB2539C0

#include "geometry_msgs/msg/Inertia.h"

#include "std_msgs/msg/Header.h"

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"


#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_InertiaStamped
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_Inertia inertia;
} geometry_msgs_msg_InertiaStamped;

 extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t geometry_msgs_msg_InertiaStamped_desc;

#define geometry_msgs_msg_InertiaStamped__alloc() \
((geometry_msgs_msg_InertiaStamped*) dds_alloc (sizeof (geometry_msgs_msg_InertiaStamped)));

#define geometry_msgs_msg_InertiaStamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_InertiaStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_INERTIASTAMPED_H_A755285C0F43AA37DD2BDA7BFB2539C0 */
