/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/PointStamped.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\PointStamped.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POINTSTAMPED_H_1CD67C71306D680ACE56508579C9CF7C
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POINTSTAMPED_H_1CD67C71306D680ACE56508579C9CF7C

#include "geometry_msgs\msg\Point.h"

#include "std_msgs\msg\Header.h"

#include "dds/ddsc/dds_public_impl.h"



#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_PointStamped
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_Point point;
} geometry_msgs_msg_PointStamped;

 extern const dds_topic_descriptor_t geometry_msgs_msg_PointStamped_desc;

#define geometry_msgs_msg_PointStamped__alloc() \
((geometry_msgs_msg_PointStamped*) dds_alloc (sizeof (geometry_msgs_msg_PointStamped)));

#define geometry_msgs_msg_PointStamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_PointStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POINTSTAMPED_H_1CD67C71306D680ACE56508579C9CF7C */
