/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Point.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Point.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "Point.h"

static const uint32_t geometry_msgs_msg_Point_ops [] =
{
  /* Point */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_Point_desc =
{
  .m_size = sizeof (geometry_msgs_msg_Point),
  .m_align = dds_alignof (geometry_msgs_msg_Point),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "geometry_msgs::msg::Point",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = geometry_msgs_msg_Point_ops,
  .m_meta = ""
};

