/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Point32.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Point32.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POINT32_H_29B706382EBFE6FF481E98D0298DD245
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POINT32_H_29B706382EBFE6FF481E98D0298DD245

#include "dds/ddsc/dds_public_impl.h"



#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Point32
{
  float x;
  float y;
  float z;
} geometry_msgs_msg_Point32;

__declspec(dllimport) const dds_topic_descriptor_t geometry_msgs_msg_Point32_desc;

#define geometry_msgs_msg_Point32__alloc() \
((geometry_msgs_msg_Point32*) dds_alloc (sizeof (geometry_msgs_msg_Point32)));

#define geometry_msgs_msg_Point32_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Point32_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POINT32_H_29B706382EBFE6FF481E98D0298DD245 */
