/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Point.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Point.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POINT_H_99B59094914593CAE8943237D0AA6331
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POINT_H_99B59094914593CAE8943237D0AA6331

#include "dds/ddsc/dds_public_impl.h"



#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Point
{
  double x;
  double y;
  double z;
} geometry_msgs_msg_Point;

 __declspec(dllimport) const dds_topic_descriptor_t geometry_msgs_msg_Point_desc;

#define geometry_msgs_msg_Point__alloc() \
((geometry_msgs_msg_Point*) dds_alloc (sizeof (geometry_msgs_msg_Point)));

#define geometry_msgs_msg_Point_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Point_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POINT_H_99B59094914593CAE8943237D0AA6331 */
