/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Polygon.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Polygon.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POLYGON_H_8B2CAD7BA758FB2EBF800836252B6BB1
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POLYGON_H_8B2CAD7BA758FB2EBF800836252B6BB1

#include "geometry_msgs\msg\Point32.h"

#include "dds/ddsc/dds_public_impl.h"



#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_GEOMETRY_MSGS_MSG_POINT32_DEFINED
#define DDS_SEQUENCE_GEOMETRY_MSGS_MSG_POINT32_DEFINED
typedef struct dds_sequence_geometry_msgs_msg_Point32
{
  uint32_t _maximum;
  uint32_t _length;
  struct geometry_msgs_msg_Point32 *_buffer;
  bool _release;
} dds_sequence_geometry_msgs_msg_Point32;

#define dds_sequence_geometry_msgs_msg_Point32__alloc() \
((dds_sequence_geometry_msgs_msg_Point32*) dds_alloc (sizeof (dds_sequence_geometry_msgs_msg_Point32)));

#define dds_sequence_geometry_msgs_msg_Point32_allocbuf(l) \
((struct geometry_msgs_msg_Point32 *) dds_alloc ((l) * sizeof (struct geometry_msgs_msg_Point32)))
#endif /* DDS_SEQUENCE_GEOMETRY_MSGS_MSG_POINT32_DEFINED */

typedef struct geometry_msgs_msg_Polygon
{
  dds_sequence_geometry_msgs_msg_Point32 points;
} geometry_msgs_msg_Polygon;

 extern const dds_topic_descriptor_t geometry_msgs_msg_Polygon_desc;

#define geometry_msgs_msg_Polygon__alloc() \
((geometry_msgs_msg_Polygon*) dds_alloc (sizeof (geometry_msgs_msg_Polygon)));

#define geometry_msgs_msg_Polygon_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Polygon_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POLYGON_H_8B2CAD7BA758FB2EBF800836252B6BB1 */
