/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/PolygonStamped.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\PolygonStamped.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POLYGONSTAMPED_H_D512A59B9ED63898E817B99A690B781E
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POLYGONSTAMPED_H_D512A59B9ED63898E817B99A690B781E

#include "geometry_msgs\msg\Polygon.h"

#include "std_msgs\msg\Header.h"

#include "dds/ddsc/dds_public_impl.h"



#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_PolygonStamped
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_Polygon polygon;
} geometry_msgs_msg_PolygonStamped;

 extern const dds_topic_descriptor_t geometry_msgs_msg_PolygonStamped_desc;

#define geometry_msgs_msg_PolygonStamped__alloc() \
((geometry_msgs_msg_PolygonStamped*) dds_alloc (sizeof (geometry_msgs_msg_PolygonStamped)));

#define geometry_msgs_msg_PolygonStamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_PolygonStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POLYGONSTAMPED_H_D512A59B9ED63898E817B99A690B781E */
