/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/PoseStamped.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\PoseStamped.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSESTAMPED_H_4095F014D6CFABA329F7A7F55CD8CFEA
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSESTAMPED_H_4095F014D6CFABA329F7A7F55CD8CFEA

#include "geometry_msgs/msg/Pose.h"

#include "std_msgs/msg/Header.h"

#include "dds/ddsc/dds_public_impl.h"



#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_PoseStamped
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_Pose pose;
} geometry_msgs_msg_PoseStamped;

 extern const dds_topic_descriptor_t geometry_msgs_msg_PoseStamped_desc;

#define geometry_msgs_msg_PoseStamped__alloc() \
((geometry_msgs_msg_PoseStamped*) dds_alloc (sizeof (geometry_msgs_msg_PoseStamped)));

#define geometry_msgs_msg_PoseStamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_PoseStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSESTAMPED_H_4095F014D6CFABA329F7A7F55CD8CFEA */
