/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Pose.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Pose.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSE_H_8455270F6111D0300FAFB2724CB71744
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSE_H_8455270F6111D0300FAFB2724CB71744

#include "geometry_msgs\msg\Point.h"

#include "geometry_msgs\msg\Quaternion.h"

#include "dds/ddsc/dds_public_impl.h"



#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Pose
{
  struct geometry_msgs_msg_Point position;
  struct geometry_msgs_msg_Quaternion orientation;
} geometry_msgs_msg_Pose;

 __declspec(dllimport) const dds_topic_descriptor_t geometry_msgs_msg_Pose_desc; //work

#define geometry_msgs_msg_Pose__alloc() \
((geometry_msgs_msg_Pose*) dds_alloc (sizeof (geometry_msgs_msg_Pose)));

#define geometry_msgs_msg_Pose_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Pose_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSE_H_8455270F6111D0300FAFB2724CB71744 */
