/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Pose2D.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Pose2D.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSE2D_H_E47AB1F4BA1F9326D3DAB70C974B39CB
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSE2D_H_E47AB1F4BA1F9326D3DAB70C974B39CB

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"


#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Pose2D
{
  double x;
  double y;
  double theta;
} geometry_msgs_msg_Pose2D;

 extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t geometry_msgs_msg_Pose2D_desc;

#define geometry_msgs_msg_Pose2D__alloc() \
((geometry_msgs_msg_Pose2D*) dds_alloc (sizeof (geometry_msgs_msg_Pose2D)));

#define geometry_msgs_msg_Pose2D_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Pose2D_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSE2D_H_E47AB1F4BA1F9326D3DAB70C974B39CB */
