/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Pose2D.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Pose2D.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "Pose2D.h"

static const uint32_t geometry_msgs_msg_Pose2D_ops [] =
{
  /* Pose2D */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Pose2D, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Pose2D, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Pose2D, theta),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_Pose2D_desc =
{
  .m_size = sizeof (geometry_msgs_msg_Pose2D),
  .m_align = dds_alignof (geometry_msgs_msg_Pose2D),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "geometry_msgs::msg::Pose2D",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = geometry_msgs_msg_Pose2D_ops,
  .m_meta = ""
};

