/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/PoseArray.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\PoseArray.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSEARRAY_H_06616C6DBFC44E2F3186F916C0BB7477
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSEARRAY_H_06616C6DBFC44E2F3186F916C0BB7477

#include "geometry_msgs/msg/Pose.h"

#include "std_msgs/msg/Header.h"

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"


#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_GEOMETRY_MSGS_MSG_POSE_DEFINED
#define DDS_SEQUENCE_GEOMETRY_MSGS_MSG_POSE_DEFINED
typedef struct dds_sequence_geometry_msgs_msg_Pose
{
  uint32_t _maximum;
  uint32_t _length;
  struct geometry_msgs_msg_Pose *_buffer;
  bool _release;
} dds_sequence_geometry_msgs_msg_Pose;

#define dds_sequence_geometry_msgs_msg_Pose__alloc() \
((dds_sequence_geometry_msgs_msg_Pose*) dds_alloc (sizeof (dds_sequence_geometry_msgs_msg_Pose)));

#define dds_sequence_geometry_msgs_msg_Pose_allocbuf(l) \
((struct geometry_msgs_msg_Pose *) dds_alloc ((l) * sizeof (struct geometry_msgs_msg_Pose)))
#endif /* DDS_SEQUENCE_GEOMETRY_MSGS_MSG_POSE_DEFINED */

typedef struct geometry_msgs_msg_PoseArray
{
  struct std_msgs_msg_Header header;
  dds_sequence_geometry_msgs_msg_Pose poses;
} geometry_msgs_msg_PoseArray;

 extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t geometry_msgs_msg_PoseArray_desc;

#define geometry_msgs_msg_PoseArray__alloc() \
((geometry_msgs_msg_PoseArray*) dds_alloc (sizeof (geometry_msgs_msg_PoseArray)));

#define geometry_msgs_msg_PoseArray_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_PoseArray_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSEARRAY_H_06616C6DBFC44E2F3186F916C0BB7477 */
