/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/PoseArray.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\PoseArray.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "PoseArray.h"

static const uint32_t geometry_msgs_msg_PoseArray_ops [] =
{
  /* PoseArray */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_PoseArray, header), (3u << 16u) + 8u /* Header */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (geometry_msgs_msg_PoseArray, poses), sizeof (geometry_msgs_msg_Pose), (4u << 16u) + 16u /* Pose */,
  DDS_OP_RTS,

  /* Header */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (std_msgs_msg_Header, frame_id),
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS,

  /* Pose */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Pose, position), (3u << 16u) + 7u /* Point */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Pose, orientation), (3u << 16u) + 11u /* Quaternion */,
  DDS_OP_RTS,

  /* Point */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, z),
  DDS_OP_RTS,

  /* Quaternion */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, z),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, w),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_PoseArray_desc =
{
  .m_size = sizeof (geometry_msgs_msg_PoseArray),
  .m_align = dds_alignof (geometry_msgs_msg_PoseArray),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "geometry_msgs::msg::PoseArray",
  .m_keys = NULL,
  .m_nops = 21,
  .m_ops = geometry_msgs_msg_PoseArray_ops,
  .m_meta = ""
};

