/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/PoseStamped.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\PoseStamped.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "PoseStamped.h"

static const uint32_t geometry_msgs_msg_PoseStamped_ops [] =
{
  /* PoseStamped */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_PoseStamped, header), (3u << 16u) + 7u /* Header */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_PoseStamped, pose), (3u << 16u) + 15u /* Pose */,
  DDS_OP_RTS,

  /* Header */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (std_msgs_msg_Header, frame_id),
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS,

  /* Pose */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Pose, position), (3u << 16u) + 7u /* Point */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Pose, orientation), (3u << 16u) + 11u /* Quaternion */,
  DDS_OP_RTS,

  /* Point */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, z),
  DDS_OP_RTS,

  /* Quaternion */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, z),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, w),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_PoseStamped_desc =
{
  .m_size = sizeof (geometry_msgs_msg_PoseStamped),
  .m_align = dds_alignof (geometry_msgs_msg_PoseStamped),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "geometry_msgs::msg::PoseStamped",
  .m_keys = NULL,
  .m_nops = 21,
  .m_ops = geometry_msgs_msg_PoseStamped_ops,
  .m_meta = ""
};

