/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Pose.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Pose.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "Pose.h"

static const uint32_t geometry_msgs_msg_Pose_ops [] =
{
  /* Pose */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Pose, position), (3u << 16u) + 7u /* Point */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Pose, orientation), (3u << 16u) + 11u /* Quaternion */,
  DDS_OP_RTS,

  /* Point */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, z),
  DDS_OP_RTS,

  /* Quaternion */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, z),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, w),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_Pose_desc =
{
  .m_size = sizeof (geometry_msgs_msg_Pose),
  .m_align = dds_alignof (geometry_msgs_msg_Pose),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "geometry_msgs::msg::Pose",
  .m_keys = NULL,
  .m_nops = 12,
  .m_ops = geometry_msgs_msg_Pose_ops,
  .m_meta = ""
};

