/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/PoseWithCovarianceStamped.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\PoseWithCovarianceStamped.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSEWITHCOVARIANCESTAMPED_H_B3BC2F36F8305C1F629608C65150C629
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSEWITHCOVARIANCESTAMPED_H_B3BC2F36F8305C1F629608C65150C629

#include "geometry_msgs\msg\PoseWithCovariance.h"

#include "std_msgs\msg\Header.h"

#include "dds/ddsc/dds_public_impl.h"



#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_PoseWithCovarianceStamped
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_PoseWithCovariance pose;
} geometry_msgs_msg_PoseWithCovarianceStamped;

 __declspec(dllimport) const dds_topic_descriptor_t geometry_msgs_msg_PoseWithCovarianceStamped_desc;

#define geometry_msgs_msg_PoseWithCovarianceStamped__alloc() \
((geometry_msgs_msg_PoseWithCovarianceStamped*) dds_alloc (sizeof (geometry_msgs_msg_PoseWithCovarianceStamped)));

#define geometry_msgs_msg_PoseWithCovarianceStamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_PoseWithCovarianceStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSEWITHCOVARIANCESTAMPED_H_B3BC2F36F8305C1F629608C65150C629 */
