/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/PoseWithCovarianceStamped.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\PoseWithCovarianceStamped.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "PoseWithCovarianceStamped.h"

static const uint32_t geometry_msgs_msg_PoseWithCovarianceStamped_ops [] =
{
  /* PoseWithCovarianceStamped */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_PoseWithCovarianceStamped, header), (3u << 16u) + 7u /* Header */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_PoseWithCovarianceStamped, pose), (3u << 16u) + 15u /* PoseWithCovariance */,
  DDS_OP_RTS,

  /* Header */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (std_msgs_msg_Header, frame_id),
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS,

  /* PoseWithCovariance */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_PoseWithCovariance, pose), (3u << 16u) + 7u /* Pose */,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_PoseWithCovariance, covariance), 36u,
  DDS_OP_RTS,

  /* Pose */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Pose, position), (3u << 16u) + 7u /* Point */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Pose, orientation), (3u << 16u) + 11u /* Quaternion */,
  DDS_OP_RTS,

  /* Point */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Point, z),
  DDS_OP_RTS,

  /* Quaternion */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, z),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, w),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_PoseWithCovarianceStamped_desc =
{
  .m_size = sizeof (geometry_msgs_msg_PoseWithCovarianceStamped),
  .m_align = dds_alignof (geometry_msgs_msg_PoseWithCovarianceStamped),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "geometry_msgs::msg::PoseWithCovarianceStamped",
  .m_keys = NULL,
  .m_nops = 24,
  .m_ops = geometry_msgs_msg_PoseWithCovarianceStamped_ops,
  .m_meta = ""
};

