/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/PoseWithCovariance.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\PoseWithCovariance.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSEWITHCOVARIANCE_H_D80832531FE17ED8E795AF00A92BDE9D
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSEWITHCOVARIANCE_H_D80832531FE17ED8E795AF00A92BDE9D

#include "geometry_msgs/msg/Pose.h"

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"


#ifdef __cplusplus
extern "C" {
#endif

typedef double geometry_msgs_msg_double__36[36];

#define geometry_msgs_msg_double__36__alloc() \
((geometry_msgs_msg_double__36*) dds_alloc (sizeof (geometry_msgs_msg_double__36)));

typedef struct geometry_msgs_msg_PoseWithCovariance
{
  struct geometry_msgs_msg_Pose pose;
  geometry_msgs_msg_double__36 covariance;
} geometry_msgs_msg_PoseWithCovariance;

 extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t geometry_msgs_msg_PoseWithCovariance_desc;

#define geometry_msgs_msg_PoseWithCovariance__alloc() \
((geometry_msgs_msg_PoseWithCovariance*) dds_alloc (sizeof (geometry_msgs_msg_PoseWithCovariance)));

#define geometry_msgs_msg_PoseWithCovariance_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_PoseWithCovariance_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_POSEWITHCOVARIANCE_H_D80832531FE17ED8E795AF00A92BDE9D */
