/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/QuaternionStamped.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\QuaternionStamped.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_QUATERNIONSTAMPED_H_B93BD6FFE09230DCFFF90A0DB8B4DA8A
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_QUATERNIONSTAMPED_H_B93BD6FFE09230DCFFF90A0DB8B4DA8A

#include "geometry_msgs/msg/Quaternion.h"

#include "std_msgs/msg/Header.h"

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"


#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_QuaternionStamped
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_Quaternion quaternion;
} geometry_msgs_msg_QuaternionStamped;

 extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t geometry_msgs_msg_QuaternionStamped_desc;

#define geometry_msgs_msg_QuaternionStamped__alloc() \
((geometry_msgs_msg_QuaternionStamped*) dds_alloc (sizeof (geometry_msgs_msg_QuaternionStamped)));

#define geometry_msgs_msg_QuaternionStamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_QuaternionStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_QUATERNIONSTAMPED_H_B93BD6FFE09230DCFFF90A0DB8B4DA8A */
