/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Quaternion.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Quaternion.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_QUATERNION_H_4CB550C1BE4C2DDB3FFE7123648E0034
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_QUATERNION_H_4CB550C1BE4C2DDB3FFE7123648E0034

#include "dds/ddsc/dds_public_impl.h"



#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Quaternion
{
  double x;
  double y;
  double z;
  double w;
} geometry_msgs_msg_Quaternion;

 extern const dds_topic_descriptor_t geometry_msgs_msg_Quaternion_desc;

#define geometry_msgs_msg_Quaternion__alloc() \
((geometry_msgs_msg_Quaternion*) dds_alloc (sizeof (geometry_msgs_msg_Quaternion)));

#define geometry_msgs_msg_Quaternion_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Quaternion_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_QUATERNION_H_4CB550C1BE4C2DDB3FFE7123648E0034 */
