/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Quaternion.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Quaternion.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "Quaternion.h"

static const uint32_t geometry_msgs_msg_Quaternion_ops [] =
{
  /* Quaternion */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, z),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, w),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_Quaternion_desc =
{
  .m_size = sizeof (geometry_msgs_msg_Quaternion),
  .m_align = dds_alignof (geometry_msgs_msg_Quaternion),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "geometry_msgs::msg::Quaternion",
  .m_keys = NULL,
  .m_nops = 5,
  .m_ops = geometry_msgs_msg_Quaternion_ops,
  .m_meta = ""
};

