/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Transform.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Transform.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "Transform.h"

static const uint32_t geometry_msgs_msg_Transform_ops [] =
{
  /* Transform */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Transform, translation), (3u << 16u) + 7u /* Vector3 */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Transform, rotation), (3u << 16u) + 11u /* Quaternion */,
  DDS_OP_RTS,

  /* Vector3 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, z),
  DDS_OP_RTS,

  /* Quaternion */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, z),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Quaternion, w),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_Transform_desc =
{
  .m_size = sizeof (geometry_msgs_msg_Transform),
  .m_align = dds_alignof (geometry_msgs_msg_Transform),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "geometry_msgs::msg::Transform",
  .m_keys = NULL,
  .m_nops = 12,
  .m_ops = geometry_msgs_msg_Transform_ops,
  .m_meta = ""
};

