/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/TransformStamped.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\TransformStamped.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_TRANSFORMSTAMPED_H_E7A38DD6B7019A3E32C9074CE6988A62
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_TRANSFORMSTAMPED_H_E7A38DD6B7019A3E32C9074CE6988A62

#include "geometry_msgs/msg/Transform.h"

#include "std_msgs/msg/Header.h"

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"


#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_TransformStamped
{
  struct std_msgs_msg_Header header;
  char * child_frame_id;
  struct geometry_msgs_msg_Transform transform;
} geometry_msgs_msg_TransformStamped;

extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t geometry_msgs_msg_TransformStamped_desc;

#define geometry_msgs_msg_TransformStamped__alloc() \
((geometry_msgs_msg_TransformStamped*) dds_alloc (sizeof (geometry_msgs_msg_TransformStamped)));

#define geometry_msgs_msg_TransformStamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_TransformStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_TRANSFORMSTAMPED_H_E7A38DD6B7019A3E32C9074CE6988A62 */
