/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Transform.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Transform.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_TRANSFORM_H_91A70308AF0A8E6DC38D7467ECD978F0
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_TRANSFORM_H_91A70308AF0A8E6DC38D7467ECD978F0

#include "geometry_msgs\msg\Quaternion.h"

#include "geometry_msgs\msg\Vector3.h"

#include "dds/ddsc/dds_public_impl.h"



#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Transform
{
  struct geometry_msgs_msg_Vector3 translation;
  struct geometry_msgs_msg_Quaternion rotation;
} geometry_msgs_msg_Transform;

__declspec(dllimport) const dds_topic_descriptor_t geometry_msgs_msg_Transform_desc;

#define geometry_msgs_msg_Transform__alloc() \
((geometry_msgs_msg_Transform*) dds_alloc (sizeof (geometry_msgs_msg_Transform)));

#define geometry_msgs_msg_Transform_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Transform_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_TRANSFORM_H_91A70308AF0A8E6DC38D7467ECD978F0 */
