/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/TwistWithCovarianceStamped.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\TwistWithCovarianceStamped.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_TWISTWITHCOVARIANCESTAMPED_H_25E2E26C7BE765AEEFDCA5BFA3469177
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_TWISTWITHCOVARIANCESTAMPED_H_25E2E26C7BE765AEEFDCA5BFA3469177

#include "geometry_msgs/msg/TwistWithCovariance.h"

#include "std_msgs/msg/Header.h"

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"


#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_TwistWithCovarianceStamped
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_TwistWithCovariance twist;
} geometry_msgs_msg_TwistWithCovarianceStamped;

 extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t geometry_msgs_msg_TwistWithCovarianceStamped_desc;

#define geometry_msgs_msg_TwistWithCovarianceStamped__alloc() \
((geometry_msgs_msg_TwistWithCovarianceStamped*) dds_alloc (sizeof (geometry_msgs_msg_TwistWithCovarianceStamped)));

#define geometry_msgs_msg_TwistWithCovarianceStamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_TwistWithCovarianceStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_TWISTWITHCOVARIANCESTAMPED_H_25E2E26C7BE765AEEFDCA5BFA3469177 */
