/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/TwistWithCovariance.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\TwistWithCovariance.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_TWISTWITHCOVARIANCE_H_8163DCE31A9E5B0B06E5B5674B9F3555
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_TWISTWITHCOVARIANCE_H_8163DCE31A9E5B0B06E5B5674B9F3555

#include "geometry_msgs/msg/Twist.h"

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"


#ifdef __cplusplus
extern "C" {
#endif

typedef double geometry_msgs_msg_double__36[36];

#define geometry_msgs_msg_double__36__alloc() \
((geometry_msgs_msg_double__36*) dds_alloc (sizeof (geometry_msgs_msg_double__36)));

typedef struct geometry_msgs_msg_TwistWithCovariance
{
  struct geometry_msgs_msg_Twist twist;
  geometry_msgs_msg_double__36 covariance;
} geometry_msgs_msg_TwistWithCovariance;

 extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t geometry_msgs_msg_TwistWithCovariance_desc;

#define geometry_msgs_msg_TwistWithCovariance__alloc() \
((geometry_msgs_msg_TwistWithCovariance*) dds_alloc (sizeof (geometry_msgs_msg_TwistWithCovariance)));

#define geometry_msgs_msg_TwistWithCovariance_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_TwistWithCovariance_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_TWISTWITHCOVARIANCE_H_8163DCE31A9E5B0B06E5B5674B9F3555 */
