/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Vector3.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Vector3.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_VECTOR3_H_B727EF7F162CA2BC48F0B6E85A0E0797
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_VECTOR3_H_B727EF7F162CA2BC48F0B6E85A0E0797

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Vector3
{
  double x;
  double y;
  double z;
} geometry_msgs_msg_Vector3;

 extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t geometry_msgs_msg_Vector3_desc;

#define geometry_msgs_msg_Vector3__alloc() \
((geometry_msgs_msg_Vector3*) dds_alloc (sizeof (geometry_msgs_msg_Vector3)));

#define geometry_msgs_msg_Vector3_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Vector3_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_VECTOR3_H_B727EF7F162CA2BC48F0B6E85A0E0797 */
