/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Vector3Stamped.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Vector3Stamped.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_VECTOR3STAMPED_H_3AB4D0E40E62F1E07F807A4A93F99F32
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_VECTOR3STAMPED_H_3AB4D0E40E62F1E07F807A4A93F99F32

#include "geometry_msgs\msg\Vector3.h"

#include "std_msgs\msg\Header.h"

#include "dds/ddsc/dds_public_impl.h"



#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Vector3Stamped
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_Vector3 vector;
} geometry_msgs_msg_Vector3Stamped;

 extern const dds_topic_descriptor_t geometry_msgs_msg_Vector3Stamped_desc;

#define geometry_msgs_msg_Vector3Stamped__alloc() \
((geometry_msgs_msg_Vector3Stamped*) dds_alloc (sizeof (geometry_msgs_msg_Vector3Stamped)));

#define geometry_msgs_msg_Vector3Stamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Vector3Stamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_VECTOR3STAMPED_H_3AB4D0E40E62F1E07F807A4A93F99F32 */
