/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Vector3Stamped.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Vector3Stamped.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "Vector3Stamped.h"

static const uint32_t geometry_msgs_msg_Vector3Stamped_ops [] =
{
  /* Vector3Stamped */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Vector3Stamped, header), (3u << 16u) + 7u /* Header */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (geometry_msgs_msg_Vector3Stamped, vector), (3u << 16u) + 15u /* Vector3 */,
  DDS_OP_RTS,

  /* Header */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (std_msgs_msg_Header, frame_id),
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS,

  /* Vector3 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_Vector3Stamped_desc =
{
  .m_size = sizeof (geometry_msgs_msg_Vector3Stamped),
  .m_align = dds_alignof (geometry_msgs_msg_Vector3Stamped),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "geometry_msgs::msg::Vector3Stamped",
  .m_keys = NULL,
  .m_nops = 13,
  .m_ops = geometry_msgs_msg_Vector3Stamped_ops,
  .m_meta = ""
};

