/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Vector3.c
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Vector3.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#include "Vector3.h"

static const uint32_t geometry_msgs_msg_Vector3_ops [] =
{
  /* Vector3 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (geometry_msgs_msg_Vector3, z),
  DDS_OP_RTS
};

const dds_topic_descriptor_t geometry_msgs_msg_Vector3_desc =
{
  .m_size = sizeof (geometry_msgs_msg_Vector3),
  .m_align = dds_alignof (geometry_msgs_msg_Vector3),
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "geometry_msgs::msg::Vector3",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = geometry_msgs_msg_Vector3_ops,
  .m_meta = ""
};

