/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/Wrench.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\Wrench.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_WRENCH_H_DDDA82871B401D40CDEF353CADC7FFE5
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_WRENCH_H_DDDA82871B401D40CDEF353CADC7FFE5

#include "geometry_msgs/msg/Vector3.h"

#include "dds/ddsc/dds_public_impl.h"

#include "CycloneRos.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Wrench
{
  struct geometry_msgs_msg_Vector3 force;
  struct geometry_msgs_msg_Vector3 torque;
} geometry_msgs_msg_Wrench;

 extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t geometry_msgs_msg_Wrench_desc;

#define geometry_msgs_msg_Wrench__alloc() \
((geometry_msgs_msg_Wrench*) dds_alloc (sizeof (geometry_msgs_msg_Wrench)));

#define geometry_msgs_msg_Wrench_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Wrench_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_WRENCH_H_DDDA82871B401D40CDEF353CADC7FFE5 */
