/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/geometry_msgs\msg/WrenchStamped.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\geometry_msgs\msg\WrenchStamped.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_WRENCHSTAMPED_H_AFBB427689C420F34341458271A7F2A7
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_WRENCHSTAMPED_H_AFBB427689C420F34341458271A7F2A7

#include "geometry_msgs\msg\Wrench.h"

#include "std_msgs\msg\Header.h"

#include "dds/ddsc/dds_public_impl.h"



#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_WrenchStamped
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_Wrench wrench;
} geometry_msgs_msg_WrenchStamped;

 extern const dds_topic_descriptor_t geometry_msgs_msg_WrenchStamped_desc;

#define geometry_msgs_msg_WrenchStamped__alloc() \
((geometry_msgs_msg_WrenchStamped*) dds_alloc (sizeof (geometry_msgs_msg_WrenchStamped)));

#define geometry_msgs_msg_WrenchStamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_WrenchStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_GEOMETRY_MSGS_MSG_WRENCHSTAMPED_H_AFBB427689C420F34341458271A7F2A7 */
