/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Dev\IDLUnrealCompiler\Generated/builtin_interfaces\msg/Duration.h
  Source: C:\Dev\IDLUnrealCompiler\Messages\builtin_interfaces\msg\Duration.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_BUILTIN_INTERFACES_MSG_DURATION_H_F2AFE59292773EA2623CB4C054B9E96B
#define DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_BUILTIN_INTERFACES_MSG_DURATION_H_F2AFE59292773EA2623CB4C054B9E96B

#include "dds/ddsc/dds_public_impl.h"
#include "CycloneRos.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct builtin_interfaces_msg_Duration
{
  int32_t sec;
  uint32_t nanosec;
} builtin_interfaces_msg_Duration;

extern CYCLONE_ROS_EXPORT const dds_topic_descriptor_t builtin_interfaces_msg_Duration_desc;

#define builtin_interfaces_msg_Duration__alloc() \
((builtin_interfaces_msg_Duration*) dds_alloc (sizeof (builtin_interfaces_msg_Duration)));

#define builtin_interfaces_msg_Duration_free(d,o) \
dds_sample_free ((d), &builtin_interfaces_msg_Duration_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__DEV_IDLUNREALCOMPILER_GENERATED_BUILTIN_INTERFACES_MSG_DURATION_H_F2AFE59292773EA2623CB4C054B9E96B */
