/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSTFMessage.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSTFMessage.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "tf2_msgs/msg/TFMessage.h"


#include "GeometryMsgs/Msg/ROSTransformStamped.h"

#include "ROSTFMessage.generated.h" 





USTRUCT(Blueprintable)
struct FROSTFMessage
{
    GENERATED_BODY()

    FROSTFMessage()
    {

    };
    
    FROSTFMessage(const TArray<FROSTransformStamped>& InTransforms)
        : Transforms(InTransforms)
    {}
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FROSTransformStamped> Transforms;
    

    void DDSToUE(const tf2_msgs_msg_TFMessage& InData);
    void UEToDDS(tf2_msgs_msg_TFMessage& OutData);
};



DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSTFMessageCallback, const FROSTFMessage, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UTFMessage_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

public:
    
    UPROPERTY(BlueprintAssignable)
    FROSTFMessageCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */
    
    UFUNCTION(BlueprintCallable)
    void GetData(FROSTFMessage& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSTFMessage Input);

private:
    tf2_msgs_msg_TFMessage* Data;
};