/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSDuration.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSDuration.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "builtin_interfaces/msg/Duration.h"
#include "ROSDuration.generated.h" 

USTRUCT(Blueprintable)
struct FROSDuration
{
	GENERATED_BODY()

	FROSDuration()
	{

	};

    
	UPROPERTY(EditAnywhere)
	int32 Sec = 0;
    
	UPROPERTY(EditAnywhere)
	unsigned int Nanosec = 0;

	
	void DDSToUE(const builtin_interfaces_msg_Duration& InData);
	void UEToDDS(builtin_interfaces_msg_Duration& OutData);
};
