/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSDuration.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSDuration.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "builtin_interfaces/msg/Duration.h"
#include "ROSDuration.generated.h" 

/** @addtogroup {NameDoxygenMessageContainer}
  * @brief {NameDoxygenMessageContainer}
  *
  * @{
  */
USTRUCT(Blueprintable)
struct FROSDuration
{
	GENERATED_BODY()

public:
	/**
	* @cond
	*/
	FROSDuration()
	{

	};
	/**
	 * @endcond
	 */

    
	UPROPERTY(EditAnywhere)
	int32 Sec;
    
	UPROPERTY(EditAnywhere)
	unsigned int Nanosec;
    

	/**
	 * @cond
	 */
	void DDSToUE (const builtin_interfaces_msg_Duration& InData) 
	{
		Sec = InData.sec;
		Nanosec = InData.nanosec;
	};

	void UEToDDS (builtin_interfaces_msg_Duration& OutData) 
	{
		OutData.sec = Sec;
		OutData.nanosec = Nanosec;
	};
    
	/**
	 * @endcond
	 */
};
/** @} */
