/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSTime.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSTime.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "Topic/TopicProxy.h"

#include "Utils/ConvertUtils.h"

#include "builtin_interfaces/msg/Time.h"

#include "ROSTime.generated.h" 

USTRUCT(Blueprintable)
struct FROSTime
{
    GENERATED_BODY()

    FROSTime()
    {

    };

    
    UPROPERTY(EditAnywhere)
    int32 Sec = 0;
    
    UPROPERTY(EditAnywhere)
    unsigned int Nanosec = 0;
    

    void DDSToUE(const builtin_interfaces_msg_Time& InData);
    void UEToDDS(builtin_interfaces_msg_Time& OutData);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSTimeCallback, const FROSTime, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UTime_TopicProxy : public UTopicProxy
{
    GENERATED_BODY()

    UPROPERTY(BlueprintAssignable)
    FROSTimeCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSTime& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSTime Input);

private:
    builtin_interfaces_msg_Time* Data;
};