/*****************************************************************//**
 * Generated by Morse IDL to UE Translator.
 * @file   ROSDeleteEntity.h
 * @brief  File containing data structures and the definition of the message generated from the IDL.
 *         Idl Type : ROSDeleteEntity.idl
 *         
 * @author Nicolas B.
 * @date   December 2023
 * @copyright Copyright 2023 Nicolas Brugie. All rights reserved.
 *********************************************************************/

#pragma once 
#include "CoreMinimal.h" 
#include "SimulationInterfaces/Msg/ROSResult.h"
#include "Topic/MRSTopicProxy.h"
#include "Utils/ConvertUtils.h"


#include "simulation_interfaces/srv/DeleteEntity.h"

#include "ROSDeleteEntity.generated.h" 



USTRUCT(Blueprintable)
struct FROSDeleteEntity_Request
{
    GENERATED_BODY()

    FROSDeleteEntity_Request()
    {

    };

    
    UPROPERTY(EditAnywhere)
    FString Entity;
    

    void DDSToUE(const simulation_interfaces_srv_DeleteEntity_Request& InData);
    void UEToDDS(simulation_interfaces_srv_DeleteEntity_Request& OutData);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSDeleteEntity_RequestCallback, const FROSDeleteEntity_Request, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UDeleteEntity_Request_TopicProxy : public UMRSTopicProxy
{
    GENERATED_BODY()

    UPROPERTY(BlueprintAssignable)
    FROSDeleteEntity_RequestCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSDeleteEntity_Request& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSDeleteEntity_Request Input);

private:
    simulation_interfaces_srv_DeleteEntity_Request* Data;
};

USTRUCT(Blueprintable)
struct FROSDeleteEntity_Response
{
    GENERATED_BODY()

    FROSDeleteEntity_Response()
    {

    };

    
    UPROPERTY(EditAnywhere)
    FROSResult Result;
    

    void DDSToUE(const simulation_interfaces_srv_DeleteEntity_Response& InData);
    void UEToDDS(simulation_interfaces_srv_DeleteEntity_Response& OutData);
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FROSDeleteEntity_ResponseCallback, const FROSDeleteEntity_Response, Data);

UCLASS(BlueprintType, Blueprintable)
class MORSEROSDATAMODEL_API UDeleteEntity_Response_TopicProxy : public UMRSTopicProxy
{
    GENERATED_BODY()

    UPROPERTY(BlueprintAssignable)
    FROSDeleteEntity_ResponseCallback OnDataChanged;

    /** Begin implement TopicProxy Interface */
    virtual void Initialize() override;
    virtual void Terminate() override;
    virtual const dds_topic_descriptor_t* GetTypeDesc() override;
    virtual void* Get() override;
    virtual void ExecuteMessageCallback() override;
    /** End implement TopicProxy Interface */

    UFUNCTION(BlueprintCallable)
    void GetData(FROSDeleteEntity_Response& Output);

    UFUNCTION(BlueprintCallable)
    void SetData(FROSDeleteEntity_Response Input);

private:
    simulation_interfaces_srv_DeleteEntity_Response* Data;
};